DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Chaos Dwarf');
DELETE FROM options WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Chaos Dwarf');
DELETE FROM units WHERE faction = 'Chaos Dwarf';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Chaos Dwarf', 'Drazhoath the Ashen, Prohet of Hashut', 'Lords', 570, 1, 1),
    ('Chaos Dwarf', 'Sorcerer-Prophet', 'Lords', 265, 1, 1),
    ('Chaos Dwarf', 'Daemonsmith Sorcerer', 'Heroes', 95, 1, 1),
    ('Chaos Dwarf', 'Infernal Castellan', 'Heroes', 105, 1, 1),
    ('Chaos Dwarf', 'Hobgoblin Khan', 'Heroes', 40, 1, 1),
    ('Chaos Dwarf', 'Bull Centaur Taur´ruk', 'Heroes', 155, 1, 1),
    ('Chaos Dwarf', 'Chaos Dwarf Infernal Guard', 'Core', 12, 10, 100),
    ('Chaos Dwarf', 'Hobgoblin Cutthroats', 'Core', 4, 20, 100),
    ('Chaos Dwarf', 'Chaos Dwarf Infernal Ironsworn', 'Special', 17, 10, 100),
    ('Chaos Dwarf', 'Bull Centaur Renders', 'Special', 40, 3, 30),
    ('Chaos Dwarf', 'Kdaai Fireborn', 'Special', 55, 3, 30),
    ('Chaos Dwarf', 'Magma Cannon', 'Special', 145, 1, 1),
    ('Chaos Dwarf', 'Deathshrieker Rocket Launcher', 'Special', 100, 1, 1),
    ('Chaos Dwarf', 'Iron Daemon War Engine', 'Special', 285, 1, 1),
    ('Chaos Dwarf', 'Hobgoblin Wolf Riders', 'Rare', 12, 5, 50),
    ('Chaos Dwarf', 'Dreadquake Mortar', 'Rare', 195, 1, 1),
    ('Chaos Dwarf', 'Kdaai Destroyer', 'Rare', 325, 1, 1),
    ('Chaos Dwarf', 'Hellcannon', 'Rare', 205, 1, 1),
    ('Chaos Dwarf', 'Chaos Siege Giant', 'Rare', 275, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name ='Drazhoath the Ashen, Prohet of Hashut'), 'Drazhoath', '3', 6, 4, 4, 5, 4, 2, '3', 10, 'Drazhoath(Infantry, Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Drazhoath the Ashen, Prohet of Hashut'), 'Cinderbreath', '6', 5, 0, 6, 6, 5, 3, '4', 6, 'Cinderbreath(Monster)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet'), 'Sorcerer-Prophet', '3', 5, 4, 4, 5, 3, 2, '3', 10, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet'), 'Great Taurus', '6', 5, 0, 6, 5, 4, 3, '4', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet'), 'Bale Taurus', '6', 5, 0, 6, 6, 5, 3, '4', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer'), 'Daemonsmith Sorcerer', '3', 4, 4, 4, 4, 2, 2, '2', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan'), 'Infernal Castellan', '3', 6, 4, 4, 5, 2, 3, '3', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan'), 'Hobgoblin Khan', '4', 4, 3, 4, 4, 2, 4, '3', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk'), 'Taur´ruk', '7', 5, 2, 5, 5, 4, 4, '4', 9, 'Monstrous Beast', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard'), 'Infernal', '3', 4, 3, 4, 4, 1, 2, '1', 9, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard'), 'Deathmask', '3', 5, 3, 4, 4, 1, 2, '2', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats'), 'Cutthroats', '4', 3, 3, 3, 3, 1, 2, '1', 6, 'Infantry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats'), 'Murder Boss', '4', 3, 3, 3, 3, 1, 3, '2', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn'), 'Infernal Ironsworn', '3', 5, 3, 4, 4, 1, 2, '1', 9, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn'), 'Deathmask', '3', 5, 3, 4, 4, 1, 2, '2', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders'), 'Bull Centaur Render', '7', 4, 2, 4, 5, 3, 3, '2', 8, 'Monstrous Beast', 3),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders'), 'Bull Centaur Ba´hal', '7', 4, 2, 4, 5, 3, 3, '3', 8, 'Monstrous Beast', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kdaai Fireborn'), 'Kdaai Fireborn', '6', 4, 2, 5, 4, 2, 4, '2', 7, 'Monstrous Infantry', 3),
    ((SELECT unit_id from units WHERE unit_name ='Kdaai Fireborn'), 'Kdaai Manburner', '6', 4, 2, 5, 4, 2, 4, '3', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Magma Cannon'), 'Magma Cannon', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Magma Cannon'), 'Chaos Dwarf Crew', '3', 4, 3, 3, 4, 1, 2, '1', 9, '-', 1),
    ((SELECT unit_id from units WHERE unit_name ='Deathshrieker Rocket Launcher'), 'Rocket Battery', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Deathshrieker Rocket Launcher'), 'Chaos Dwarf', '3', 4, 3, 3, 4, 1, 2, '1', 9, '-', 1),
    ((SELECT unit_id from units WHERE unit_name ='Iron Daemon War Engine'), 'Iron Daemon', '6', null, null, 8, 7, 7, null, null, null, 'Unique unit', 1),
    ((SELECT unit_id from units WHERE unit_name ='Iron Daemon War Engine'), 'Chaos Dwarf Crew', null, 4, 3, 3, null, null, 2, '3', 9, '', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders'), 'Raider', '4', 3, 3, 3, 3, 1, 2, '1', 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders'), 'Wolf Boss', '4', 3, 3, 3, 3, 1, 3, '2', 6, 'Cavalry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders'), 'Giant Wolf', '9', 3, 0, 3, 3, 1, 3, '1', 3, '-', 20),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar'), 'Mortar', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar'), 'Chaos Dwarf', '3', 4, 3, 3, 4, 1, 2, '1', 9, '-', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar'), 'Slave Ogre', '6', 3, 2, 4, 4, 3, 2, '3', 7, '-', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kdaai Destroyer'), 'Kdaai Destroyer', '9', 5, 3, 7, 6, 6, 5, '6', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hellcannon' AND faction = 'Chaos Dwarf'), 'Hellcannon', '3', 4, 3, 5, 6, 5, 1, '5', 4, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hellcannon' AND faction = 'Chaos Dwarf'), 'Chaos Dwarf Handlers', '3', 4, 3, 3, 4, 1, 2, '1', 9, '-', 3),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Siege Giant'), 'Chaos Siege Giant', '5', 4, 3, 6, 5, 6, 3, 'Special', 10, 'Monster', 1);

INSERT INTO options (unit_id, name, points, pointsPerModel) VALUES
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'May upgraded to a Lever 4 Wizard', 35, null),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'May take Magic Items up to a total of', 100, null),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'May be equipped with any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'May ride one of the following mounts', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf'), 'May upgraded to a Lever 2 Wizard', 35, null),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf'), 'May take Magic Items up to a total of', 50, null),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf'), 'May be equipped with any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'May take Magic Items up to a total of', 75, null),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'May be equipped with any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'May take Magic Items up to a total of', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'May be equipped with any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'May ride a Giant Wolf', 12, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'May take Magic Items up to a total of', 50, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'May be equipped with any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'The unit may also have one of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Upgrade one Chaos Dwarf Infernal to a Musician', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Upgrade one Chaos Dwarf Infernal to a Standard Bearer', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Upgrade one Chaos Dwarf Infernal to a Deathmask', 12, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'One unit of Chaos Dwarf Infernals in the army may have a magic standard worth up to', 50, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'May be equipped with shields', 0.5, true),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'May be equipped with one of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'Upgrade one Hobgoblin Cutthroats to a Musician', 4, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'Upgrade one Hobgoblin Cutthroats to a Standard Bearer', 8, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'Upgrade one Hobgoblin Cutthroats to a Murder Boss', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn' AND faction = 'Chaos Dwarf'), 'Upgrade one Infernal Ironsworn to a Musician', 5, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn' AND faction = 'Chaos Dwarf'), 'Upgrade one Infernal Ironsworn to a Standard Bearer', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn' AND faction = 'Chaos Dwarf'), 'Upgrade one Infernal Ironsworn to a Deathmask', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Ironsworn' AND faction = 'Chaos Dwarf'), 'Any unit of Infernal Ironsworn may have a magic standard worth up to', 50, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'May be equipped with shields', 5, true),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'May be equipped with one of the following:', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Upgrade one Render to a Musician', 5, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Upgrade one Render to a Standard Bearer', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Upgrade one Render to a Ba´hal', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'One unit of Bull Centaur Renders may have a magic standard worth up to', 50, null),
    ((SELECT unit_id from units WHERE unit_name ='Kdaai Fireborn' AND faction = 'Chaos Dwarf'), 'Upgrade one Fireborn to a Manburner', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Deathshrieker Rocket Launcher' AND faction = 'Chaos Dwarf'), 'The Deathshrieker Rocket may be mounted on a Steam Carriage if at least one Iron Daemon is in the army', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Deathshrieker Rocket Launcher' AND faction = 'Chaos Dwarf'), 'The Deathshrieker Rocket may be Hellbound', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Iron Daemon War Engine' AND faction = 'Chaos Dwarf'), 'The Iron Daemon may be Hellbound', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Iron Daemon War Engine' AND faction = 'Chaos Dwarf'), 'The Steam Cannonade may be replaced with a Skullcracker', 30, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'May be equipped with shields (the unit will no longer be counted as Fast Cavalry)', 1, true),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'May be equipped with one of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'Upgrade one Wolf Rider to a Musician', 5, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'Upgrade one Wolf Rider to a Standard Bearer', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'Upgrade one Wolf Rider to a Wolf Boss', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar' AND faction = 'Chaos Dwarf'), 'The Dreadquake Mortar may be crewed by an additional Slave Ogre (note this adds three extra wounds rather than one)', 20, true),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar' AND faction = 'Chaos Dwarf'), 'It may be mounted on a Steam Carriage if at least one Iron Daemon is in the army', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Dreadquake Mortar' AND faction = 'Chaos Dwarf'), 'The Dreadquake Mortar may be Hellbound', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Kdaai Destroyer' AND faction = 'Chaos Dwarf'), 'None', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Siege Giant' AND faction = 'Chaos Dwarf'), 'Runes of Hate', 25, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Siege Giant' AND faction = 'Chaos Dwarf'), 'Scaling Spikes', 10, null);

INSERT INTO options (unit_id, name, points, pointsPerModel, parent_option) VALUES
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Pistol', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Naphtha Bombs', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Blood of Hashut (one use)', 20, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Great Taurus', 145, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May ride one of the following mounts')),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Lammasu', 195, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May ride one of the following mounts')),
    ((SELECT unit_id from units WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf'), 'Bale Taurus', 225, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Sorcerer-Prophet' AND faction = 'Chaos Dwarf' AND name ='May ride one of the following mounts')),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf'), 'Pistol', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf'), 'Naphtha Bombs', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Daemonsmith Sorcerer' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'Shield', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'Pistol', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'Great Weapon', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf'), 'Fireglaive', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Infernal Castellan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'Light Armour', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'Shield', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'Additional Hand Weapon (if on foot only)', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf'), 'Spear (mounted only)', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Khan' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'Blackshard Armour', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'Shield', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'Additional Hand Weapon', 10, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf'), 'Great Weapon', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Taur´ruk' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Great Weapon', 3, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf' AND name ='The unit may also have one of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Fireglaives', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf' AND name ='The unit may also have one of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'Hailshot Blunderbusses', 6, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf' AND name ='The unit may also have one of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf'), 'The Overseermay be equipped with a pistol for 2 points and/ or a Naptha Bomb for', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Dwarf Infernal Guard' AND faction = 'Chaos Dwarf' AND name ='Upgrade one Chaos Dwarf Infernal to a Deathmask')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'Additional hand weapons', 0.5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf'), 'Bows', 1, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Cutthroats' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Additional Hand Weapon', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Great Weapons', 10, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf'), 'Spears', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bull Centaur Renders' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Iron Daemon War Engine' AND faction = 'Chaos Dwarf'), '(in this case only the impact hits and Thunderstomp of the machine, not the crew, become magical attaks)', 0, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Iron Daemon War Engine' AND faction = 'Chaos Dwarf' AND name ='The Iron Daemon may be Hellbound')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'Spears', 1, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:')),
    ((SELECT unit_id from units WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf'), 'bows', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Hobgoblin Wolf Riders' AND faction = 'Chaos Dwarf' AND name ='May be equipped with any of the following:'));
