DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Dark Elves');
DELETE FROM units WHERE faction = 'Dark Elves';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Dark Elves', 'Malekith', 'Lords', 510, 1, 1),
    ('Dark Elves', 'Morathi', 'Lords', 375, 1, 1),
    ('Dark Elves', 'Hellebron', 'Lords', 310, 1, 1),
    ('Dark Elves', 'Malus Darkblade', 'Lords', 295, 1, 1),
    ('Dark Elves', 'Dreadlord', 'Lords', 140, 1, 1),
    ('Dark Elves', 'Supreme Sorceress', 'Lords', 185, 1, 1),
    ('Dark Elves', 'High BeastMaster', 'Lords', 300, 1, 1),
    ('Dark Elves', 'Black Ark Fleetmaster', 'Lords', 155, 1, 1),
    ('Dark Elves', 'Shadowblade', 'Heroes', 245, 1, 1),
    ('Dark Elves', 'Lokhir Fellheart', 'Heroes', 235, 1, 1),
    ('Dark Elves', 'Kouran Darkhand', 'Heroes', 180, 1, 1),
    ('Dark Elves', 'Tullaris Dreadbringer', 'Heroes', 155, 1, 1),
    ('Dark Elves', 'Sorceress', 'Heroes', 80, 1, 1),
    ('Dark Elves', 'Master', 'Heroes', 70, 1, 1),
    ('Dark Elves', 'Death Hag', 'Heroes', 85, 1, 1),
    ('Dark Elves', 'Khainithe Assassin', 'Heroes', 90, 1, 1),
    ('Dark Elves', 'Dreadspears', 'Core', 9, 10, 100),
    ('Dark Elves', 'Bleakswords', 'Core', 9, 10, 100),
    ('Dark Elves', 'Darkshards', 'Core', 12, 10, 100),
    ('Dark Elves', 'Black Ark Corsairs', 'Core', 9, 10, 100),
    ('Dark Elves', 'Dark Riders', 'Core', 16, 5, 50),
    ('Dark Elves', 'Witch Elves', 'Core', 11, 10, 100),
    ('Dark Elves', 'Cold One Knights', 'Special', 30, 5, 50),
    ('Dark Elves', 'Black Guard of Naggarond', 'Special', 15, 10, 100),
    ('Dark Elves', 'Shades', 'Special', 16, 5, 50),
    ('Dark Elves', 'Cold One Chariot', 'Special', 115, 1, 1),
    ('Dark Elves', 'Har Ganeth Executioners', 'Special', 12, 10, 100),
    ('Dark Elves', 'Reaper Bolt Thrower', 'Special', 70, 1, 1),
    ('Dark Elves', 'Harpies', 'Special', 15, 5, 50),
    ('Dark Elves', 'Scourgerunner Chariot', 'Special', 150, 1, 1),
    ('Dark Elves', 'War Hydra', 'Special', 160, 1, 1),
    ('Dark Elves', 'Doomfire Warlocks', 'Rare', 25, 5, 50),
    ('Dark Elves', 'Bloodwrack Medusa', 'Rare', 90, 1, 1),
    ('Dark Elves', 'Kharibdyss', 'Rare', 160, 1, 1),
    ('Dark Elves', 'Bloodwrack Shrine', 'Rare', 175, 1, 1),
    ('Dark Elves', 'Sister of Slaughter', 'Rare', 15, 10, 100);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name ='Malekith'), 'Malekith', '5', 8, 7, 5, 4, 3, 8, '4', 10, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Malekith'), 'Seraphon(Black Dragon)', '6', 7, 0, 6, 6, 6, 3, '6', 8, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Morathi'), 'Morathi', '5', 5, 4, 3, 3, 3, 6, '3', 10, 'Monstrous Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Morathi'), 'Sulephet(Dark Pegasus)', '8', 4, 0, 4, 4, 3, 4, '3', 6, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Hellebron'), 'Hellebron', '5', 7, 7, 4, 3, 3, 9, '4', 10, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Malus Darkblade'), 'Malus Darkblade', '5', 7, 7, 4, 3, 3, 8, '4', 10, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Malus Darkblade'), 'Spite(Cold One)', '7', 3, 0, 4, 4, 1, 2, '3', 4, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Dreadlord'), 'Dreadlord', '5', 7, 7, 4, 3, 3, 8, '4', 10, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Supreme Sorceress'), 'Supreme Sorceress', '5', 4, 4, 3, 3, 3, 5, '1', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='High BeastMaster'), 'High BeastMaster', '5', 7, 7, 4, 3, 3, 8, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Ark Fleetmaster'), 'Black Ark Fleetmaster', '5', 6, 6, 4, 3, 3, 7, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Shadowblade'), 'Shadowblade', '6', 10, 10, 4, 3, 2, 10, '3', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lokhir Fellheart'), 'Lokhir Fellheart', '5', 6, 6, 4, 3, 2, 7, '3', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kouran Darkhand'), 'Kouran Darkhand', '5', 9, 6, 4, 3, 2, 7, '3', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tullaris Dreadbringer'), 'Tullaris Dreadbringer', '5', 6, 6, 4, 3, 2, 7, '3', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Sorceress'), 'Sorceress', '5', 4, 4, 3, 3, 2, 5, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Master'), 'Master', '5', 6, 6, 4, 3, 2, 7, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Death Hag'), 'Death Hag', '5', 6, 6, 4, 3, 2, 7, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Khainithe Assassin'), 'Khainithe Assassin', '5', 9, 9, 4, 3, 2, 10, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dreadspears'), 'Dark Elf Warrior', '5', 4, 4, 3, 3, 1, 5, '1', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Dreadspears'), 'Lordling', '5', 4, 4, 3, 3, 1, 5, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bleakswords'), 'Dark Elf Warrior', '5', 4, 4, 3, 3, 1, 5, '1', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Bleakswords'), 'Lordling', '5', 4, 4, 3, 3, 1, 5, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Darkshards'), 'Dark Elf Warrior', '5', 4, 4, 3, 3, 1, 5, '1', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Darkshards'), 'Guardmaster', '5', 4, 5, 3, 3, 1, 5, '1', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Ark Corsairs'), 'Black Ark Corsair', '5', 4, 4, 3, 3, 1, 5, '1', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Black Ark Corsairs'), 'Reaver', '5', 4, 4, 3, 3, 1, 5, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dark Riders'), 'Dark Rider', '5', 4, 4, 3, 3, 1, 5, '1', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Dark Riders'), 'Herald', '5', 4, 5, 3, 3, 1, 5, '1', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dark Riders'), 'Dark Steed', '9', 3, 0, 3, 3, 1, 4, '1', 5, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Witch Elves'), 'Witch Elf', '5', 4, 4, 3, 3, 1, 6, '1', 8, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Witch Elves'), 'Hag', '5', 4, 4, 3, 3, 1, 6, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Knights'), 'Cold One Knight', '5', 5, 4, 4, 3, 1, 6, '1', 9, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Knights'), 'Dread Knight', '5', 5, 4, 4, 3, 1, 6, '2', 9, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Knights'), 'Cold One', '7', 3, 0, 4, 4, 1, 2, '2', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Black Guard of Naggarond'), 'Black Guard', '5', 5, 4, 3, 3, 1, 6, '2', 9, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Black Guard of Naggarond'), 'Tower Master','5', 5, 4, 3, 3, 1, 6, '3', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Shades'), 'Shade', '5', 5, 5, 3, 3, 1, 5, '1', 8, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Shades'), 'Bloodshade','5', 5, 6, 3, 3, 1, 5, '1', 8, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Chariot'), 'Cold One Chariot', null, null, null, 5, 5, 4, null, null, null, 'Chariot(Armour Save 3+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Chariot'), 'Knight Charioteer', null, 5, 4, 4, null, null, 6, '1', 9, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Chariot'), 'Cold One', '7', 3, null, 4, null, null, 2, '2', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Har Ganeth Executioners'), 'Executioner','5', 5, 4, 4, 3, 1, 5, '1', 9, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Har Ganeth Executioners'), 'Draich Master', '5', 5, 4, 4, 3, 1, 5, '2', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Reaper Bolt Thrower'), 'Reaper Bolt Thrower', null, null, null, null, 7, 2, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Reaper Bolt Thrower'), 'Dark Elf Crew', '5', 4, 4, 3, 3, 1, 5, '1', 8, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Harpies' AND faction = 'Dark Elves'), 'Harpies', '5', 3, 0, 3, 3, 1, 5, '2', 6, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Scourgerunner Chariot'), 'Scourgerunner Chariot', null, null, null, 4, 4, 4, null, null, null, 'Chariot(Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Scourgerunner Chariot'), 'Beastmaster Crew', null, 4, 4, 3, null, null, 5, '2', 8, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Scourgerunner Chariot'), 'Dark Steed', '9', 3, 0, 3, null, null, 4, '1', 5, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='War Hydra'), 'War Hydra', '6', 4, 4, 5, 5, 5, 2, '3+*', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doomfire Warlocks'), 'Doomfire Warlock', '5', 4, 4, 4, 3, 1, 5, '2', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Doomfire Warlocks'), 'Master of Warlocks', '5', 4, 4, 4, 3, 1, 5, '3', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doomfire Warlocks'), 'Dark Steed', '9', 3, 0, 3, 3, 1, 4, '1', 5, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Bloodwrack Medusa'), 'Bloodwrack Medusa', '7', 5, 5, 4, 4, 3, 5, '3', 2, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kharibdyss'), 'Kharibdyss', '1', 4, 3, 4, 5, 3, 2, '2', 9, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodwrack Shrine'), 'Bloodwrack Shrine', '5', null, null, 5, 6, 5, null, null, null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodwrack Shrine'), 'Shrinekeeper', null, 4, 4, 3, null, null, 5, '1', 8, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Bloodwrack Shrine'), 'Bloodwrack Medusa', null, 5, 5, 4, null, null, 5, '3', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Sister of Slaughter'), 'Sister of Slaughter', '5', 6, 4, 3, 3, 1, 6, '2', 9, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Sister of Slaughter'), 'Handmaiden of Shards', '5', 6, 4, 3, 3, 1, 6, '3', 9, 'Infantry', 1);