DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Lizardmen');
DELETE FROM units WHERE faction = 'Lizardmen';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Lizardmen', 'Lord Mazdamundi', 'Lords', 780, 1, 1),
    ('Lizardmen', 'Lord Kroak', 'Lords', 400, 1, 1),
    ('Lizardmen', 'Kroq-Gar' ,'Lords' , 520, 1, 1),
    ('Lizardmen', 'Tehenhauin','Lords' , 230, 1, 1),
    ('Lizardmen', 'Slann Mage-Priest','Lords' , 300, 1, 1),
    ('Lizardmen', 'Saurus Oldblood','Lords' , 140, 1, 1),
    ('Lizardmen', 'Chakax' ,'Heroes' , 270, 1, 1),
    ('Lizardmen', 'Gor-Rox','Heroes' , 185, 1, 1),
    ('Lizardmen', 'Tetto`eko','Heroes' , 185, 1, 1),
    ('Lizardmen', 'Tiktaqto','Heroes' , 170, 1, 1),
    ('Lizardmen', 'Oxyotl','Heroes' , 120, 1, 1),
    ('Lizardmen', 'Skink Priest','Heroes' , 65, 1, 1),
    ('Lizardmen', 'Saurus Scar-Veteran','Heroes' , 80, 1, 1),
    ('Lizardmen', 'Skink Chief','Heroes' , 40, 1, 1),
    ('Lizardmen', 'Saurus Warriors' ,'Core' , 11, 10, 100),
    ('Lizardmen', 'Skink Cohort','Core' , 5, 10, 100),
    ('Lizardmen', 'Skink Skirmishers','Core' , 7, 10, 100),
    ('Lizardmen', 'Temple Guard','Special' , 14, 10, 100),
    ('Lizardmen', 'Jungle Swarms','Special' , 35, 2, 20),
    ('Lizardmen', 'Chameleon Skinks','Special' , 13, 5, 50),
    ('Lizardmen', 'Cold One Riders','Special' , 30, 5, 50),
    ('Lizardmen', 'Kroxigor','Special' , 50, 3, 30),
    ('Lizardmen', 'Terradon Riders','Special' , 35, 1, 1),
    ('Lizardmen', 'Stegadon','Special' , 215, 1, 1),
    ('Lizardmen', 'Bastiladon','Special' , 150, 1, 1),
    ('Lizardmen', 'Ripperdactyl Riders','Special' , 40, 3, 30),
    ('Lizardmen', 'Ancient Stegadon','Rare' , 230, 1, 1),
    ('Lizardmen', 'Salamander Hunting Pack','Rare' , 80, 1, 1),
    ('Lizardmen', 'Razordon Hunting Pack','Rare' , 65, 1, 1),
    ('Lizardmen', 'Troglodon','Rare' , 200, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Lord Mazdamundi'), 'Lord Mazdamundi', '4', 2, 3, 3, 4, 5, 2, '1', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lord Mazdamundi'), 'Zlaaq (Ancient Stegadon)', '6', 3, 0, 6, 6, 5, 1, '3', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lord Kroak'), 'Lord Kroak', '4', 1, 1, 3, 5, 6, 1, '1', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kroq-Gar'), 'Kroq-Gar', '4', 6, 0, 5, 5, 3, 3, '5', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kroq-Gar'), 'Grymloq (Carnosaur)', '7', 3, 0, 7, 5, 5, 2, '5', 5, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tehenhauin'), 'Tehenhauin', '6', 6, 5, 4, 3, 3, 6, '3', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Slann Mage-Priest'), 'Slann Mage-Priest', '4', 2, 3, 3, 4, 5, 2, '1', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Saurus Oldblood'), 'Saurus Oldblood', '4', 6, 0, 5, 5, 3, 3, '5', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chakax'), 'Chakax', '4', 5, 0, 5, 5, 2, 3, '4', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gor-Rox'), 'Gor-Rox', '4', 5, 0, 5, 6, 2, 3, '4', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tetto`eko'), 'Tetto`eko', '6', 4, 5, 4, 3, 2, 6, '3', 7, 'Monstrous Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tetto`eko'), 'Zwup (Terradon)', '2', 3, 0, 4, 3, 2, 2, '1', 3, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Oxyotl'), 'Oxyotl', '6', 4, 6, 4, 3, 2, 6, '3', 7, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skink Priest'), 'Skink Priest', '6', 2, 3, 3, 2, 2, 4, '1', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Saurus Scar-Veteran'), 'Saurus Scar-Veteran', '4', 5, 0, 5, 5, 2, 3, '4', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skink Chief'), 'Skink Chief', '6', 4, 5, 4, 3, 2, 6, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Saurus Warriors'), 'Saurus Warrior', '4', 3, 0, 4, 4, 1, 1, '2', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Saurus Warriors'), 'Saurus Leader', '4', 3, 0, 4, 4, 1, 1, '3', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skink Cohort'), 'Skink', '6', 2, 3, 3, 2, 1, 4, '1', 5, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Skink Cohort'), 'Skink Brave', '6', 2, 3, 3, 2, 1, 4, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skink Cohort'), 'Kroxigor', '6', 3, 0, 5, 4, 3, 1, '3', 7, 'Monstrous Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Skink Skirmishers'), 'Skink Skirmisher', '6', 2, 3, 3, 2, 1, 4, '1', 5, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Skink Skirmishers'), 'Patrol Leader', '6', 2, 4, 3, 2, 1, 4, '1', 5, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Temple Guard'), 'Temple Guard', '4', 4, 0, 4, 4, 1, 2, '2', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Temple Guard'), 'Revered Guardian', '4', 4, 0, 4, 4, 1, 2, '3', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Jungle Swarms'), 'Jungle Swarm', '5', 3, 0, 2, 2, 5, 1, '5', 10, 'Swarm', 20),
    ((SELECT unit_id from units WHERE unit_name ='Chameleon Skinks'), 'Chameleon Skink', '6', 2, 4, 3, 2, 1, 4, '1', 5, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Chameleon Skinks'), 'Stalker', '6', 2, 5, 3, 2, 1, 4, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Riders'), 'Cold One Riders', '4', 4, 0, 4, 4, 1, 2, '2', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Riders'), 'Pack Leader', '4', 4, 0, 4, 4, 1, 2, '3', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cold One Riders'), 'Cold One', '7', 3, null, 4, null, null, 2, '2', null, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Kroxigor'), 'Kroxigor', '6', 3, 0, 5, 4, 3, 1, '3', 7, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Kroxigor'), 'Kroxigor Ancient', '6', 3, 0, 5, 4, 3, 1, '4', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Terradon Riders'), 'Terradon Rider', '6', 2, 3, 3, 2, 1, 4, '1', 5, 'Monstrous Cavalry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Terradon Riders'), 'Sky Leader', '6', 2, 4, 3, 2, 1, 4, '1', 5, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Terradon Riders'), 'Terradon', '2', 3, 0, 4, 3, 2, 2, '1', 3, null, 30),
    ((SELECT unit_id from units WHERE unit_name ='Stegadon'), 'Stegadon', '6', 3, 0, 5, 6, 5, 2, '4', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Stegadon'), 'Skink Crew', null, 2, 3, 3, null, null, 4, '1', null, null, 5),
    ((SELECT unit_id from units WHERE unit_name ='Bastiladon'), 'Bastiladon','4', 3, 0, 4, 5, 4, 1, '3', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bastiladon'), 'Skink Crew', null, 2, 3, 3, null, null, 4, '1', null, null, 4),
    ((SELECT unit_id from units WHERE unit_name ='Ripperdactyl Riders'), 'Ripperdactyl Rider', '6', 2, 3, 3, 2, 1, 4, '1', 5, 'Monstrous Cavalry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Ripperdactyl Riders'), 'Ripperdactyl Brave', '6', 2, 3, 3, 2, 1, 4, '2', 5, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ripperdactyl Riders'), 'Ripperdactyl','2', 3, 0, 4, 3, 2, 3, '2', 3, null, 30),
    ((SELECT unit_id from units WHERE unit_name ='Ancient Stegadon'), 'Ancient Stegadon', '6', 3, 0, 6, 6, 5, 1, '3', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ancient Stegadon'), 'Skink Crew', null, 2, 3, 3, null, null, 4, '1', null, null, 5),
    ((SELECT unit_id from units WHERE unit_name ='Salamander Hunting Pack'), 'Salamander', '6', 3, 3, 5, 4, 3, 4, '2', 4, 'Monstrous Beast', 1),
    ((SELECT unit_id from units WHERE unit_name ='Salamander Hunting Pack'), 'Skink Handler', '6', 2, 3, 3, 2, 1, 4, '1', 5, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Razordon Hunting Pack'), 'Razordon', '6', 3, 3, 5, 4, 3, 4, '2', 4, 'Monstrous Beast', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razordon Hunting Pack'), 'Skink Handler', '6', 2, 3, 3, 2, 1, 4, '1', 5, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Troglodon'), 'Troglodon', '7', 3, 3, 5, 5, 5, 2, '3', 5, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Troglodon'), 'Skink Oracle Rider', null, 2, 3, 3, null, null, 4, '1', 6, null, 1);
