DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Skaven');
DELETE FROM units WHERE faction = 'Skaven';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Skaven', 'Lord Skrolk' ,'Lords' , 470, 1, 1),
    ('Skaven', 'Thanquol & BoneRipper','Lords' , 450, 1, 1),
    ('Skaven', 'Ikit Claw','Lords' , 395, 1, 1),
    ('Skaven', 'Throt the Unclean','Lords' , 225, 1, 1),
    ('Skaven', 'Queek Headtaker','Lords' , 215, 1, 1),
    ('Skaven', 'Vermin Lord' ,'Lords' , 500, 1, 1),
    ('Skaven', 'Warlord','Lords' , 90, 1, 1),
    ('Skaven', 'Grey Seer','Lords' , 240, 1, 1),
    ('Skaven', 'Deathmaster Snikch' ,'Heroes' , 270, 1, 1),
    ('Skaven', 'Tretch Craventail','Heroes' , 145, 1, 1),
    ('Skaven', 'Assassin','Heroes' , 120, 1, 1),
    ('Skaven', 'Warlock Engineer','Heroes' , 15, 1, 1),
    ('Skaven', 'Chieftain' ,'Heroes' , 45, 1, 1),
    ('Skaven', 'Plague Priest','Heroes' , 100, 1, 1),
    ('Skaven', 'Clanrats' ,'Core' , 4, 20, 200),
    ('Skaven', 'Stormvermin','Core' , 7, 10, 100),
    ('Skaven', 'Skavenslaves','Core' , 2, 20, 200),
    ('Skaven', 'Night Runners','Core' , 7, 10, 100),
    ('Skaven', 'Giant Rats','Core' , 3, 5, 50),
    ('Skaven', 'Rat Swarm','Core' , 25, 2, 10),
    ('Skaven', 'Gutter Runners','Special' , 12, 5, 15),
    ('Skaven', 'Rat Ogres','Special' , 40, 3, 30),
    ('Skaven', 'Plague Monks','Special' , 7, 10, 100),
    ('Skaven', 'Plague Censer Bearers','Special' , 16, 5, 50),
    ('Skaven', 'Warplock Jezzails','Special' , 20, 3, 30),
    ('Skaven', 'Poisoned Wind Globadiers','Special' , 10, 5, 15),
    ('Skaven', 'Hell Pit Abomination','Rare' , 235, 1, 1),
    ('Skaven', 'Doomwheel','Rare' , 150, 1, 1),
    ('Skaven', 'Warp Lightning Cannon','Rare' , 90, 1, 1),
    ('Skaven', 'Plagueclaw Catapult','Rare' , 100, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Lord Skrolk'), 'Lord Skrolk', '5', 6, 4, 4, 5, 3, 6, '4', 7, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Thanquol & BoneRipper'), 'Thanquol', '5', 3, 3, 3, 4, 3, 6, '1', 7, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Thanquol & BoneRipper'), 'BoneRipper', '5', 3, 1, 5, 5, 3, 1, '4', 10, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ikit Claw'), 'Ikit Claw', '5', 5, 3, 5, 4, 3, 3, '2', 7, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Throt the Unclean'), 'Throt the Unclean', '6', 6, 3, 4, 4, 3, 6, '4', 7, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Queek Headtaker'), 'Queek Headtaker', '5', 7, 4, 4, 4, 3, 7, '6', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Vermin Lord'), 'Vermin Lord', '8', 8, 4, 6, 5, 5, 10, '5', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Warlord'), 'Warlord', '5', 6, 4, 4, 4, 3, 7, '4', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grey Seer'), 'Grey Seer', '5', 3, 3, 3, 4, 3, 5, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Deathmaster Snikch'), 'Deathmaster Snikch', '6', 8, 6, 4, 4, 2, 10, '6', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tretch Craventail'), 'Tretch Craventail', '5', 5, 4, 4, 4, 2, 6, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Assassin'), 'Assassin', '6', 6, 5, 4, 4, 2, 8, '3', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Warlock Engineer'), 'Warlock Engineer', '5', 3, 3, 3, 3, 2, 4, '1', 5, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chieftain'), 'Chieftain', '5', 5, 4, 4, 4, 2, 6, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plague Priest'), 'Plague Priest', '5', 5, 3, 4, 5, 2, 5, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Clanrats'), 'Clanrat', '5', 3, 3, 3, 3, 1, 4, '1', 5, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Clanrats'), 'Clawleader', '5', 3, 3, 3, 3, 1, 4, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Stormvermin'), 'Stormvermin', '5', 4, 3, 3, 3, 1, 5, '1', 5, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Stormvermin'), 'Fangleader', '5', 4, 3, 3, 3, 1, 5, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skavenslaves'), 'Skavenslave', '5', 2, 2, 3, 3, 1, 4, '1', 2, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Skavenslaves'), 'Pawleader', '5', 2, 2, 3, 3, 1, 4, '2', 2, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Runners'), 'Night Runner', '6', 3, 3, 3, 3, 1, 5, '1', 6, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Night Runners'), 'Nightleader', '6', 3, 4, 3, 3, 1, 5, '1', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Giant Rats'), 'Giant Rat', '6', 3, 1, 3, 3, 1, 4, '1', 3, 'Infantry', 3),
    ((SELECT unit_id from units WHERE unit_name ='Giant Rats'), 'Packmaster','6', 3, 3, 3, 3, 1, 4, '1', 5, 'Infantry', 8),
    ((SELECT unit_id from units WHERE unit_name ='Rat Swarm'), 'Rat Swarm', '6', 3, 0, 2, 2, 5, 4, '5', 10, 'Swarm', 10),
    ((SELECT unit_id from units WHERE unit_name ='Gutter Runners'), 'Gutter Runner', '6', 4, 4, 3, 3, 1, 5, '1', 7, 'Infantry', 15),
    ((SELECT unit_id from units WHERE unit_name ='Gutter Runners'), 'Deathrunner', '6', 4, 4, 3, 3, 1, 5, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Rat Ogres'), 'Rat Ogre', '6', 3, 1, 5, 4, 3, 4, '3', 5, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Rat Ogres'), 'Master-bred Rat Ogre', '6', 4, 1, 5, 4, 3, 5, '4', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Rat Ogres'), 'Packmaster', '6', 3, 3, 3, 3, 1, 4, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plague Monks'), 'Plague Monk', '5', 3, 3, 3, 4, 1, 3, '1', 5, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Plague Monks'), 'Bringer-of-the-Word', '5', 3, 3, 3, 4, 1, 3, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plague Censer Bearers'), 'Censer Bearer', '5', 3, 3, 3, 4, 1, 3, '2', 5, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Plague Censer Bearers'), 'Plague Chanter', '5', 3, 3, 3, 4, 1, 3, '3', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Warplock Jezzails'), 'Jezzail Team', '5', 3, 3, 3, 3, 1, 3, '2', 5, 'Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Warplock Jezzails'), 'Sharpshooter', '5', 3, 4, 3, 3, 1, 3, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Poisoned Wind Globadiers'), 'Globadier', '5', 3, 3, 3, 3, 1, 4, '1', 5, 'Infantry', 15),
    ((SELECT unit_id from units WHERE unit_name ='Poisoned Wind Globadiers'), 'Bombardier', '5', 3, 4, 3, 3, 1, 4, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hell Pit Abomination'), 'Hell Pit Abomination', '3D6', 3, 1, 6, 5, 6, 4, '*', 8, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doomwheel'), 'Doomwheel', '3D6', null, null, 6, 6, 5, null, '*', null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doomwheel'), 'Crew (Warlock & Rats)', null, 3, 3, 2, null, null, 4, '2D6', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Warp Lightning Cannon'), 'Cannon', null, null, null, null, 6, 4, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Warp Lightning Cannon'), 'Engineer & Crew', '5', 3, 3, 3, 3, null, 3, '3', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Plagueclaw Catapult'), 'Plagueclaw Catapult', null, null, null, null, 6, 4, null, null, null, 'War Machine(Stone Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plagueclaw Catapult'), 'Plague Monk Crew', '5', 3, 3, 3, 4, null, 3, 'D6', 7, null, 3);
