DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Orcs & Goblins');
DELETE FROM units WHERE faction = 'Orcs & Goblins';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Orcs & Goblins', 'Gorbad Ironclaw' ,'Lords' , 375, 1, 1),
    ('Orcs & Goblins', 'Azhag the Slaughterer','Lords' , 550, 1, 1),
    ('Orcs & Goblins', 'Grimgor Ironhide','Lords' , 355, 1, 1),
    ('Orcs & Goblins', 'Wurrzag Da Great Green Prophet','Lords' , 350, 1, 1),
    ('Orcs & Goblins', 'Grom the Paunch of Misty Mountain','Lords' , 285, 1, 1),
    ('Orcs & Goblins', 'Skarsnik, Warlord of the Eight Peaks' ,'Lords' , 275, 1, 1),
    ('Orcs & Goblins', 'Orc Warboss','Lords' , 115, 1, 1),
    ('Orcs & Goblins', 'Savage Orc WarBoss','Lords' , 150, 1, 1),
    ('Orcs & Goblins', 'Black Orc Warboss','Lords' , 160, 1, 1),
    ('Orcs & Goblins', 'Goblin Warboss','Lords' , 65, 1, 1),
    ('Orcs & Goblins', 'Night Goblin Warboss','Lords' , 55, 1, 1),
    ('Orcs & Goblins', 'Orc Great Shaman','Lords' , 165, 1, 1),
    ('Orcs & Goblins', 'Savage Orc Great Shaman','Lords' , 170, 1, 1),
    ('Orcs & Goblins', 'Goblin Great Shaman','Lords' , 145, 1, 1),
    ('Orcs & Goblins', 'Night Goblin Great Shaman','Lords' , 140, 1, 1),
    ('Orcs & Goblins', 'Gitilla Da Hunter' ,'Heroes' , 110, 1, 1),
    ('Orcs & Goblins', 'Snagla Grobspit','Heroes' , 115, 1, 1),
    ('Orcs & Goblins', 'Orc Big Boss','Heroes' , 55, 1, 1),
    ('Orcs & Goblins', 'Savage Orc Big Boss','Heroes' , 75, 1, 1),
    ('Orcs & Goblins', 'Black Orc Big Boss','Heroes' , 90, 1, 1),
    ('Orcs & Goblins', 'Goblin Big Boss','Heroes' , 35, 1, 1),
    ('Orcs & Goblins', 'Night Goblin Big Boss','Heroes' , 30, 1, 1),
    ('Orcs & Goblins', 'Orc Shaman','Heroes' , 65, 1, 1),
    ('Orcs & Goblins', 'Savage Orc Shaman','Heroes' , 70, 1, 1),
    ('Orcs & Goblins', 'Goblin Shaman','Heroes' , 55, 1, 1),
    ('Orcs & Goblins', 'Night Goblin Shaman' ,'Heroes' , 50, 1, 1),
    ('Orcs & Goblins', 'Orc Boyz' ,'Core' , 6, 10, 100),
    ('Orcs & Goblins', 'Orc Arrer Boyz','Core' , 7, 10, 100),
    ('Orcs & Goblins', 'Savage Orcs','Core' , 8, 10, 100),
    ('Orcs & Goblins', 'Goblins','Core' , 3, 20, 200),
    ('Orcs & Goblins', 'Goblins Wolf Riders','Core' , 10, 5, 50),
    ('Orcs & Goblins', 'Night Goblins','Core' , 3, 20, 100),
    ('Orcs & Goblins', 'Forest Goblin Spider Riders','Core' , 13, 5, 50),
    ('Orcs & Goblins', 'Black Orcs','Special' , 12, 10, 100),
    ('Orcs & Goblins', 'Orc Boar Boyz','Special' , 16, 5, 50),
    ('Orcs & Goblins', 'Savage Orc Boar Boyz','Special' , 18, 5, 50),
    ('Orcs & Goblins', 'Orc Boar Chariot','Special' , 85, 1, 1),
    ('Orcs & Goblins', 'Goblin Wolf Chariot','Special' , 50, 1, 3),
    ('Orcs & Goblins', 'Goblin Spear Chukka','Special' , 35, 1, 1),
    ('Orcs & Goblins', 'Night Goblin Squig Hoppers','Special' , 12, 5, 50),
    ('Orcs & Goblins', 'Night Goblin Squig Herd','Special' , 8, 10, 100),
    ('Orcs & Goblins', 'Snotlings','Special' , 30, 2, 20),
    ('Orcs & Goblins', 'Trolls','Special' , 35, 1, 10),
    ('Orcs & Goblins', 'Goblin Rock Lobber','Rare' , 85, 1, 1),
    ('Orcs & Goblins', 'Doom Diver Catapult','Rare' , 80, 1, 1),
    ('Orcs & Goblins', 'Snotling Pump Wagon','Rare' , 45, 1, 1),
    ('Orcs & Goblins', 'Arachnarok Spider','Rare' , 290, 1, 1),
    ('Orcs & Goblins', 'Mangler Squigs','Rare' , 65, 1, 1),
    ('Orcs & Goblins', 'Stone Trolls','Rare' , 45, 1, 10),
    ('Orcs & Goblins', 'River Trolls','Rare' , 45, 1, 10),
    ('Orcs & Goblins', 'Giant','Rare' , 200, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Gorbad Ironclaw'), 'Gorbad Ironclaw', '4', 7, 3, 5, 5, 3, 5, '4', 10, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gorbad Ironclaw'), 'Gnarla the War Boar', '7', 3, 0, 4, 4, 1, 3, '1', 3, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Azhag the Slaughterer'), 'Azhag the Slaughterer', '4', 7, 3, 5, 5, 3, 5, '4', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Azhag the Slaughterer'), 'Skullmuncha', '4', 5, 0, 6, 5, 5, 3, '3', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grimgor Ironhide'), 'Grimgor Ironhide', '4', 8, 1, 5, 5, 3, 5, '5', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Wurrzag Da Great Green Prophet'), 'Wurrzag', '4', 3, 3, 4, 5, 3, 2, '1', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grom the Paunch of Misty Mountain'), 'Grom', '4', 5, 3, 4, 4, 3, 4, '4', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grom the Paunch of Misty Mountain'), 'Grom´s Chariot', null, null, null, 5, 4, 3, null, null, null, 'Chariot(Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grom the Paunch of Misty Mountain'), 'Niblet', null, 3, 3, 3, null, null, 2, '1', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Grom the Paunch of Misty Mountain'), 'Giant Wolves', '9', 3, null, 3, null, null, 3, '1', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Skarsnik, Warlord of the Eight Peaks'), 'Skarsnik', '4', 5, 3, 4, 4, 6, 5, '4', 8, 'Infantry(Special Character; Night Goblin)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skarsnik, Warlord of the Eight Peaks'), 'Gobbla', null, 5, null, 6, null, null, 4, '4', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Warboss'), 'Orc Warboss', '4', 6, 3, 5, 5, 3, 4, '4', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc WarBoss'), 'Savage Orc WarBoss', '4', 6, 3, 5, 5, 3, 4, '4', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Orc Warboss'), 'Black Orc Warboss', '4', 7, 3, 5, 5, 3, 4, '4', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Warboss'), 'Goblin Warboss', '4', 5, 3, 4, 4, 3, 4, '4', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Warboss'), 'Night Goblin Warboss', '4', 5, 3, 4, 4, 3, 5, '4', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Great Shaman'), 'Orc Great Shaman', '4', 3, 3, 4, 5, 3, 2, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Great Shaman'), 'Savage Orc Great Shaman', '4', 3, 3, 4, 5, 3, 2, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Great Shaman'), 'Goblin Great Shaman', '4', 2, 3, 3, 4, 3, 2, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Great Shaman'), 'Night Goblin Great Shaman', '4', 2, 3, 3, 4, 3, 3, '1', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gitilla Da Hunter'), 'Gitilla', '4', 4, 4, 4, 4, 2, 4, '3', 7, 'Cavalry(Special Character; Goblin)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gitilla Da Hunter'), 'Ulda the Great Wolf', '9', 3, 0, 3, 3, 1, 3, '2', 3, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Snagla Grobspit'), 'Snagla', '4', 4, 3, 4, 4, 2, 4, '3', 7, 'Cavalry(Special Character; Goblin)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Snagla Grobspit'), 'Giant Spider', '7', 3, 0, 3, 3, 1, 4, '1', 2, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Big Boss'), 'Orc Big Boss', '4', 5, 3, 4, 5, 2, 3, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Big Boss'), 'Savage Orc Big Boss', '4', 5, 3, 4, 5, 2, 3, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Orc Big Boss'), 'Black Orc Big Boss', '4', 6, 3, 4, 5, 2, 3, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Big Boss'), 'Goblin Big Boss', '4', 4, 3, 4, 4, 2, 3, '3', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Big Boss'), 'Night Goblin Big Boss', '4', 4, 3, 4, 4, 2, 4, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Shaman'), 'Orc Shaman', '4', 3, 3, 3, 4, 2, 2, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Shaman'), 'Savage Orc Shaman', '4', 3, 3, 3, 4, 2, 2, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Shaman'), 'Goblin Shaman', '4', 2, 3, 3, 3, 2, 2, '1', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Shaman'), 'Night Goblin Shaman', '4', 2, 3, 3, 3, 2, 2, '1', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boyz'), 'Orc Boy', '4', 3, 3, 3, 4, 1, 2, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boyz'), 'Orc Big ´Un', '4', 4, 3, 4, 4, 1, 2, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boyz'), 'Orc Boss', '4', 4, 3, 4, 4, 1, 2, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Arrer Boyz'), 'Orc Arrer Boy', '4', 3, 3, 3, 4, 1, 2, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Orc Arrer Boyz'), 'Orc Arrer Boy Boss', '4', 3, 4, 4, 4, 1, 2, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orcs'), 'Savage Orc', '4', 3, 3, 3, 4, 1, 2, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orcs'), 'Savage Orc Big ´Un', '4', 4, 3, 4, 4, 1, 2, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orcs'), 'Savage Orc Boss', '4', 4, 3, 4, 4, 1, 2, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblins'), 'Goblin', '4', 2, 3, 3, 3, 1, 2, '1', 6, 'Infantry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Goblins'), 'Goblin Boss','4', 2, 3, 3, 3, 1, 2, '2', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblins'), 'Nasty Skulker', '4', 2, 3, 3, 3, 1, 2, '2', 6, 'Infantry', 3),
    ((SELECT unit_id from units WHERE unit_name ='Goblins Wolf Riders'), 'Goblins Wolf Rider', '4', 2, 3, 3, 3, 1, 2, '1', 6, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Goblins Wolf Riders'), 'Goblins Wolf Rider Boss', '4', 2, 3, 3, 3, 1, 2, '2', 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblins Wolf Riders'), 'Giant Wolf','9', 3, 0, 3, 3, 1, 3, '1', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblins'), 'Night Goblin', '4', 2, 3, 3, 3, 1, 3, '1', 5, 'Infantry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblins'), 'Night Goblin Boss', '4', 2, 3, 3, 3, 1, 3, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblins'), 'Night Goblin Fanatic', '2D6', null, null, 5, 3, 1, 3, '*', 10, 'Unique', 3),
    ((SELECT unit_id from units WHERE unit_name ='Forest Goblin Spider Riders'), 'Spider Rider', '4', 2, 3, 3, 3, 1, 2, '1', 6, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Forest Goblin Spider Riders'), 'Spider Rider Boss', '4', 2, 3, 3, 3, 1, 2, 2, 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Forest Goblin Spider Riders'), 'Giant Spider', '7', 3, 0, 3, 3, 1, 4, '1', 2, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Black Orcs'), 'Black Orc', '4', 4, 3, 4, 4, 1, 2, '1', 8, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Black Orcs'), 'Black Orc Boss', '4', 5, 3, 4, 4, 1, 2, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Boyz'), 'Orc Boar Boy', '4', 3, 3, 3, 4, 1, 2, '1', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Boyz'), 'Orc Boar Boy Big ´Un', '4', 4, 3, 4, 4, 1, 2, '1', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Boyz'), 'Orc Boar Boy Boss', '4', 4, 3, 4, 4, 1, 2, '2', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Boyz'), 'War Boar', '7', 3, 0, 3, 4, 1, 3, '1', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Boar Boyz'), 'Savage Orc Boar Boy', '4', 3, 3, 3, 4, 1, 2, '1', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Boar Boyz'), 'Savage Orc Boar Boy Big ´Un', '4', 4, 3, 4, 4, 1, 2, '1', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Boar Boyz'), 'Savage Orc Boar Boy Boss', '4', 4, 3, 4, 4, 1, 2, '2', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Savage Orc Boar Boyz'), 'War Boar', '7', 3, 0, 3, 4, 1, 3, '1', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Chariot'), 'Chariot', null, null, null, 5, 4, 3, null, null, null, 'Chariot(Armour Save 4+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Chariot'), 'Orc Crew', null, 3, 3, 3, null, null, 2, '1', 7, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Orc Boar Chariot'), 'War Boar', '7', 3, null, 3, null, null, 3, '1', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Wolf Chariot'), 'Chariot', null, null, null, 5, 4, 3, null, null, null, 'Chariot(Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Wolf Chariot'), 'Goblin Crew', null, 2, 3, 3, null, null, 2, '1', 6, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Wolf Chariot'), 'Giant Wolf', '9', 3, null, 3, null, null, 3, '1', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Spear Chukka'), 'Spear Chukka', null, null, null, null, 7, 3, null, null, null, 'War Machine(Bolt Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Spear Chukka'), 'Goblin Crew', '4', 2, 3, 3, 3, 1, 2, '1', 6, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Spear Chukka'), 'Orc Bully', '4', 3, 3, 3, 4, 1, 2, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Squig Hoppers'), 'Squig Hopper', 4, 2, 3, 3, 3, 1, 3, '1', 5, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Squig Hoppers'), 'Squig', '3D6', 4, 0, 5, 3, 1, 3, '2', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Squig Herd'), 'Night Goblin Herder', '4', 2, 3, 3, 3, 1, 3, '1', 5, 'Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Night Goblin Squig Herd'), 'Cave Squig', '4', 4, 0, 5, 3, 1, 3, '2', 3, 'Infantry', 90),
    ((SELECT unit_id from units WHERE unit_name ='Snotlings'), 'Snotlings', '4', 2, 0, 2, 2, 5, 3, '5', 4, 'Swarm', 2),
    ((SELECT unit_id from units WHERE unit_name ='Trolls'), 'Troll', '6', 3, 1, 5, 4, 3, 1, '3', 4, 'Monstrous Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Rock Lobber'), 'Rock Lobber', null, null, null, null, 7, 3, null, null, null, 'War Machine(Stone Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Rock Lobber'), 'Goblin Crew', '4', 2, 3, 3, 3, 1, 2, '1', 6, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Goblin Rock Lobber'), 'Orc Bully', '4', 3, 3, 3, 4, 1, 2, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Doom Diver Catapult'), 'Catapult', null, null, null, null, 7, 3, null, null, null, 'War Machine(Stone Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doom Diver Catapult'), 'Goblin Crew', '4', 2, 3, 3, 3, 1, 2, '1', 6, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Snotling Pump Wagon'), 'Snotling Pump Wagon', '2D6', null, null, 4, 4, 3, null, null, null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Snotling Pump Wagon'), 'Snotling Crew', null, 2, 0, 2, null, null, 3, '5', 4, null, 10),
    ((SELECT unit_id from units WHERE unit_name ='Arachnarok Spider'), 'Arachnarok Spider', '7', 4, null, 5, 6, 8, 4, '8', null, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Arachnarok Spider'), 'Forest Goblin Crew', null, 2, 3, 3, null, null, 2, '1', 6, null, 8),
    ((SELECT unit_id from units WHERE unit_name ='Mangler Squigs'), 'Mangler Squigs', '3D6', null, null, 6, 4, 3, 3, '*', 3, 'Unique', 1),
    ((SELECT unit_id from units WHERE unit_name ='Stone Trolls'), 'Stone Troll', '6', 3, 1, 5, 4, 3, 1, '3', 4, 'Monstrous Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='River Trolls'), 'River Troll', '6', 3, 1, 5, 4, 3, 1, '3', 4, 'Monstrous Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Giant' AND faction = 'Orcs & Goblins'), 'Giant', '6', 3, 3, 6, 5, 6, 3, 'special', 10, 'Monster', 1);
