DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Beastmen');
DELETE FROM options WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Beastmen');
DELETE FROM units WHERE faction = 'Beastmen';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Beastmen', 'Khazrak The One-Eye', 'Lords', 270, 1, 1),
    ('Beastmen', 'Gorthor the Beastlord', 'Lords', 350, 1, 1),
    ('Beastmen', 'Malagor, The Dark Omen', 'Lords', 350, 1, 1),
    ('Beastmen', 'Taurox, The Brass Bull', 'Lords', 355, 1, 1),
    ('Beastmen', 'Beastlord', 'Lords', 145, 1, 1),
    ('Beastmen', 'Doombull', 'Lords', 235, 1, 1),
    ('Beastmen', 'Great Bray-Shaman', 'Lords', 200, 1, 1),
    ('Beastmen', 'Morghur, Master of Skulls', 'Heroes', 280, 1, 1),
    ('Beastmen', 'Slugtongue', 'Heroes', 190, 1, 1),
    ('Beastmen', 'Moonclaw, Son of Morrslieb', 'Heroes', 200, 1, 1),
    ('Beastmen', 'Wargor', 'Heroes', 85, 1, 1),
    ('Beastmen', 'Gorebull', 'Heroes', 160, 1, 1),
    ('Beastmen', 'Bray-Shaman', 'Heroes', 75, 1, 1),
    ('Beastmen', 'Gors', 'Core', 7, 10, 200),
    ('Beastmen', 'Ungors', 'Core', 5, 10, 200),
    ('Beastmen', 'Ungor Raiders', 'Core', 6, 5, 10),
    ('Beastmen', 'Tuskgor Chariots', 'Core', 80, 1, 1),
    ('Beastmen', 'Chaos Warhounds', 'Core', 6, 5, 200),
    ('Beastmen', 'Minotaurs', 'Special', 55, 3, 200),
    ('Beastmen', 'Centigors', 'Special', 25, 5, 200),
    ('Beastmen', 'Harpies', 'Special', 11, 5, 10),
    ('Beastmen', 'Bestigors', 'Special', 12, 10, 200),
    ('Beastmen', 'Razorgor Chariot', 'Special', 145, 1, 1),
    ('Beastmen', 'Razorgor', 'Special', 55, 1, 100),
    ('Beastmen', 'Cygor', 'Rare', 275, 1, 1),
    ('Beastmen', 'Ghorgon', 'Rare', 275, 1, 1),
    ('Beastmen', 'Chaos Spawn', 'Rare', 55, 1, 2),
    ('Beastmen', 'Giant', 'Rare', 225, 1, 1),
    ('Beastmen', 'Jabberslythe', 'Rare', 275, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name ='Khazrak The One-Eye'), 'Khazrak', '5', 7, 1, 5, 5, 3, 5, '4', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gorthor the Beastlord'), 'Gorthor', '5', 7, 3, 5, 5, 3, 5, '5', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gorthor the Beastlord'), 'Tuskgor Chariot', null, null, null, 5, 4, 4, null, null, null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Gorthor the Beastlord'), 'Tuskgor', '7', 3, null, 4, null, null, 2, '1', null, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Malagor, The Dark Omen'), 'Malagor', '5', 5, 3, 4, 5, 3, 4, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Taurox, The Brass Bull'), 'Taurox', '6', 6, 3, 6, 6, 5, 5, '6', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord'), 'Beastlord', '5', 6, 3, 5, 5, 3, 5, '4', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Doombull'), 'Doombull', '6', 6, 3, 6, 5, 5, 5, '5', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman'), 'Great Bray-Shaman', '5', 5, 3, 4, 5, 3, 4, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Morghur, Master of Skulls'), 'Morghur', '5', 6, 3, 4, 5, 2, 4, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Slugtongue'), 'Slugtongue', '5', 4, 3, 3, 4, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Moonclaw, Son of Morrslieb'), 'Moonclaw', '5', 3, 3, 4, 4, 2, 3, '3', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Moonclaw, Son of Morrslieb'), 'Umbralok', '7', 3, 0, 4, 4, 1, 2, '3', 6, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Wargor'), 'Wargor', '5', 5, 3, 4, 5, 2, 4, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gorebull'), 'Gorebull', '6', 5, 3, 5, 5, 4, 4, '4', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bray-Shaman'), 'Bray-Shaman', '5', 4, 3, 3, 4, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gors'), 'Gor', '5', 4, 3, 3, 4, 1, 3, '1', 7, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Gors'), 'Foe-render', '5', 4, 3, 3, 4, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ungors'), 'Ungor', '5', 3, 3, 3, 3, 1, 3, '1', 6, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Ungors'), 'Halfhorn', '5', 3, 3, 3, 3, 1, 3, '2', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ungor Raiders'), 'Ungor Raider', '5', 3, 3, 3, 3, 1, 3, '1', 6, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Ungor Raiders'), 'Raider Halfhorn', '5', 3, 4, 3, 3, 1, 3, '1', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tuskgor Chariots'), 'Tuskgor Chariot', null, null, null, 5, 4, 4, null, null, null, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tuskgor Chariots'), 'Bestigor', null, 4, 3, 4, null, null, 3, '1', 7, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tuskgor Chariots'), 'Gor', null, 4, 3, 3, null, null, 3, '1', 7, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tuskgor Chariots'), 'Tuskgor', '7', 3, null, 4, null, null, 2, '1', null, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen'), 'Chaos Warhound', '7', 4, 8, 3, 3, 1, 3, '1', 5, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs'), 'Minotaur', '6', 4, 3, 5, 4, 3, 3, '3', 7, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs'), 'Bloodkine', '6', 4, 3, 5, 4, 3, 3, '4', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Centigors'), 'Centigor', '8', 4, 3, 4, 4, 1, 2, '2', 7, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Centigors'), 'Gorehoof', '8', 4, 3, 4, 4, 1, 2, '3', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Harpies' AND faction = 'Beastmen'), 'Harpy', '5', 3, 0, 3, 3, 1, 5, '2', 6, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Bestigors'), 'Bestigor', '5', 4, 3, 4, 4, 1, 3, '1', 7, 'Infantry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Bestigors'), 'Gouge-horn', '5', 4, 3, 4, 4, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razorgor Chariot'), 'Razorgor Chariot', null, null, null, 5, 5, 5, null, null, null, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razorgor Chariot'), 'Bestigor', null, 4, 3, 4, null, null, 3, '1', 7, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razorgor Chariot'), 'Gor', null, 4, 3, 3, null, null, 3, '1', 7, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razorgor Chariot'), 'Razorgor', '7', 3, null, 5, null, null, 2, '4', null, 'Chariot', 1),
    ((SELECT unit_id from units WHERE unit_name ='Razorgor'), 'Razorgor', '7', 3, 0, 5, 5, 3, 2, '4', 6, 'Infantry', null),
    ((SELECT unit_id from units WHERE unit_name ='Cygor'), 'Cygor', '7', 2, 1, 6, 5, 5, 3, '5', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ghorgon'), 'Ghorgon', '7', 4, 0, 6, 6, 6, 3, '6', 10, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Spawn' AND faction = 'Beastmen'), 'Chaos Spawn', '2D6', 3, 0, 4, 5, 3, 2, 'D6+1', 10, 'Infantry', 2),
    ((SELECT unit_id from units WHERE unit_name ='Giant' AND faction = 'Beastmen'), 'Giant', '6', 3, 3, 6, 5, 6, 2, 'special', 10, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Jabberslythe'), 'Jabberslythe', '8', 4, 4, 5, 5, 5, 3, '5', 9, 'Infantry', null);

INSERT INTO options (unit_id, name, points, pointsPerModel) VALUES
    ((SELECT unit_id from units WHERE unit_name ='Gorthor the Beastlord' AND faction = 'Beastmen'), 'Gorthor (with all equipment) and Bagrar ,ay be mounted in a Razorgor Chariot, replacing both crew, for +65 points', 65, null),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Weapons (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Armour (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'May also take:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Mount (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Weapons (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Armour (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'May also take:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Upgrade to a:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Weapons:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Mount (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Weapons (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Armour (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'May also take:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Mount (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Weapons (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Armour (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'May also take:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Upgrade to a:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Magic Items and Gift of Chaos:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Weapons:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Mount (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Gors' AND faction = 'Beastmen'), 'Upgrade one Gor to a Foe-render', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Gors' AND faction = 'Beastmen'), 'Upgrade one Gor to a musician', 5, null),
    ((SELECT unit_id from units WHERE unit_name ='Gors' AND faction = 'Beastmen'), 'Upgrade one Gor to a standard bearer', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Gors' AND faction = 'Beastmen'), 'Additional equipment:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Upgrade one Ungor to a Halfhorn', 6, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Upgrade one Ungor to a musician', 3, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Upgrade one Ungor to a standard bearer', 6, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Additional equipment:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'One Ungor unit in the army may include Ungrol', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungor Raiders' AND faction = 'Beastmen'), 'Upgrade one Ungor to a musician', 3, null),
    ((SELECT unit_id from units WHERE unit_name ='Ungor Raiders' AND faction = 'Beastmen'), 'Upgrade one Ungor to a Halfhorn', 6, null),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen'), 'The unit may choose any of the following:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Upgrade one Minotaur to a Bloodkine', 20, null),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Upgrade one Minotaur to a musician', 10, null),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Upgrade one Minotaur to a standard bearer', 20, null),
    ((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Additional Equipment (one choice only):', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'Upgrade one Centigor to a Gorehoof', 14, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'Upgrade one Centigor to a musician', 7, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'Upgrade one Centigor to a standard bearer', 14, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'The entire unit may take:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'The entire unit may replace their spears and sheilds with:', null, null),
    ((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'One Centigor unit in the army may include Ghorros Warhoof instead of a Gorehoof', 155, null),
    ((SELECT unit_id from units WHERE unit_name ='Harpies' AND faction = 'Beastmen'), 'Scouts', null, true),
    ((SELECT unit_id from units WHERE unit_name ='Bestigors' AND faction = 'Beastmen'), 'Upgrade one Bestigor to a Gouge-horn', 12, null),
    ((SELECT unit_id from units WHERE unit_name ='Bestigors' AND faction = 'Beastmen'), 'Upgrade one Bestigor to a musician', 6, null),
    ((SELECT unit_id from units WHERE unit_name ='Bestigors' AND faction = 'Beastmen'), 'Upgrade one Bestigor to a standard bearer', 12, null);

INSERT INTO options (unit_id, name, points, pointsPerModel, parent_option) VALUES
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Any up to a total of', 100, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Great weapon', 12, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Additional hand weapon', 8, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Light armour', 3, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastmen' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Heavy armour', 6, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastmen' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Shield', 3, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='May also take:')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Tuskgor Chariot', 80, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Beastlord' AND faction = 'Beastmen'), 'Razorgor Chariot', 145, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Beastlord' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Any up to a total of', 100, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Great weapon', 15, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Additional hand weapon', 8, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Light armour', 6, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Heavy armour', 12, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Doombull' AND faction = 'Beastmen'), 'Shield', 6, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Doombull' AND faction = 'Beastmen' AND name ='May also take:')),
((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Level 4 Wizard', 35, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen' AND name ='Upgrade to a:')),
((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Any up to a total of', 100, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Additional hand weapon', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen' AND name ='Weapons:')),
((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Tuskgor Chariot', 80, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen'), 'Razorgor Chariot', 145, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Great Bray-Shaman' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Any up to a total of', 50, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Great weapon', 6, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Additional hand weapon', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Light armour', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Heavy armour', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Shield', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='May also take:')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Tuskgor Chariot', 80, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Wargor' AND faction = 'Beastmen'), 'Razorgor Chariot', 145, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Wargor' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Any up to a total of', 50, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Great weapon', 10, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Additional hand weapon', 5, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='Weapons (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Light armour', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Heavy armour', 8, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='Armour (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gorebull' AND faction = 'Beastmen'), 'Shield', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gorebull' AND faction = 'Beastmen' AND name ='May also take:')),
((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Level 2 Wizard', 35, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen' AND name ='Upgrade to a:')),
((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Any up to a total of', 50, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen' AND name ='Magic Items and Gift of Chaos:')),
((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Additional hand weapon', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen' AND name ='Weapons:')),
((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Tuskgor Chariot', 80, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen'), 'Razorgor Chariot', 145, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bray-Shaman' AND faction = 'Beastmen' AND name ='Mount (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Gors' AND faction = 'Beastmen'), 'Shield or additional hand weapon', 1, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Gors' AND faction = 'Beastmen' AND name ='Additional equipment:')),
((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Spear', 1, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Ungors' AND faction = 'Beastmen' AND name ='Additional equipment:')),
((SELECT unit_id from units WHERE unit_name ='Ungors' AND faction = 'Beastmen'), 'Four-Horn instead of a Halfhorn', 75, false, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Ungors' AND faction = 'Beastmen' AND name ='One Ungor unit in the army may include Ungrol')),
((SELECT unit_id from units WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen'), 'Poisoned Attacks', 3, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen' AND name ='The unit may choose any of the following:')),
((SELECT unit_id from units WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen'), 'Scaly Skin (6+)', 1, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Chaos Warhounds' AND faction = 'Beastmen' AND name ='The unit may choose any of the following:')),
((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'may have a magic item worth up to', 25, false, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Minotaurs' AND faction = 'Beastmen' AND name ='Upgrade one Minotaur to a Bloodkine')),
((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Shields', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Minotaurs' AND faction = 'Beastmen' AND name ='Additional Equipment (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Additional hand weapons', 4, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Minotaurs' AND faction = 'Beastmen' AND name ='Additional Equipment (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Minotaurs' AND faction = 'Beastmen'), 'Great weapons', 8, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Minotaurs' AND faction = 'Beastmen' AND name ='Additional Equipment (one choice only):')),
((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'Throwing axes', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Centigors' AND faction = 'Beastmen' AND name ='The entire unit may take:')),
((SELECT unit_id from units WHERE unit_name ='Centigors' AND faction = 'Beastmen'), 'Great weapon', 2, true, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Centigors' AND faction = 'Beastmen' AND name ='The entire unit may replace their spears and sheilds with:')),
((SELECT unit_id from units WHERE unit_name ='Bestigors' AND faction = 'Beastmen'), 'may have a Gift of Chaos worth up to', 25, false, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bestigors' AND faction = 'Beastmen' AND name ='Upgrade one Bestigor to a Gouge-horn')),
((SELECT unit_id from units WHERE unit_name ='Bestigors' AND faction = 'Beastmen'), 'may have a magic standard worth up to', 50, false, (SELECT option_id FROM options LEFT JOIN units USING (unit_id) WHERE unit_name ='Bestigors' AND faction = 'Beastmen' AND name ='Upgrade one Bestigor to a standard bearer'));
