DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Bretonnia');
DELETE FROM units WHERE faction = 'Bretonnia';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Bretonnia', 'Bretonnian Lord', 'Lords', 110, 1, 1),
    ('Bretonnia', 'Prophetess of the Lady', 'Lords', 190, 1, 1),
    ('Bretonnia', 'The Green Knight', 'Lords', 275, 1, 1),
    ('Bretonnia', 'The Fay Enchantress', 'Lords', 545, 1, 1),
    ('Bretonnia', 'Paladin', 'Heroes', 60, 1, 1),
    ('Bretonnia', 'Damsel of the Lady', 'Heroes', 70, 1, 1),
    ('Bretonnia', 'Knights Errant', 'Core', 20, 5, 15),
    ('Bretonnia', 'Knights of the Realm', 'Core', 24, 5, 15),
    ('Bretonnia', 'Men-at-arms', 'Core', 5, 10, 200),
    ('Bretonnia', 'Peasant Bowmen', 'Core', 6, 10, 200),
    ('Bretonnia', 'Questing Knights', 'Special', 28, 5, 12),
    ('Bretonnia', 'Pegasus Knights', 'Special', 55, 3, 10),
    ('Bretonnia', 'Grail Religuae with Battle Pilgrims', 'Special', 118, 1, 1),
    ('Bretonnia', 'Mounted Yeoman', 'Special', 15, 5, 200),
    ('Bretonnia', 'Grail Knights', 'Rare', 38, 3, 12),
    ('Bretonnia', 'Field Trebuchet', 'Rare', 90, 1, 5);


INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name ='Bretonnian Lord'), 'Lord', '4', 6, 3, 4, 4, 3, 6, '4', 9, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bretonnian Lord'), 'Bretonnian Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bretonnian Lord'), 'Royal Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bretonnian Lord'), 'Hippogryph', '8', 4, 0, 5, 5, 4, 4, '4', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Prophetess of the Lady'), 'Prophetess', '4', 3, 3, 3, 3, 3, 3, '1', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Prophetess of the Lady'), 'Bretonnian Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Prophetess of the Lady'), 'Royal Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Prophetess of the Lady'), 'Hippogryph', '8', 4, 0, 5, 5, 4, 4, '4', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Green Knight'), 'Green Knight', '4', 7, 3, 4, 4, 3, 6, '4', 9, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Green Knight'), 'Shadow Steed', '8', 4, 0, 4, 3, 1, 4, '1', 5, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Fay Enchantress'), 'Fay Enchantress', '5', 4, 4, 3, 3, 3, 5, '1', 9, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Fay Enchantress'), 'Silvaron', '10', 5, 0, 4, 4, 3, 5, '2', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paladin'), 'Paladin', '4', 5, 3, 4, 4, 2, 5, '3', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paladin'), 'Bretonnian Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paladin'), 'Royal Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paladin'), 'Hippogryph', '8', 4, 0, 5, 5, 4, 4, '4', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Damsel of the Lady'), 'Damsel', '4', 3, 3, 3, 3, 2, 3, '1', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Damsel of the Lad'), 'Bretonnian Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Damsel of the Lad'), 'Royal Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Damsel of the Lad'), 'Hippogryph', '8', 4, 0, 5, 5, 4, 4, '4', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knights Errant'), 'Knights Errant', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Cavalry', 14),
    ((SELECT unit_id from units WHERE unit_name ='Knights Errant'), 'Cavalier', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knights Errant'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, '-', 15),
    ((SELECT unit_id from units WHERE unit_name ='Knights of the Realm'), 'Knights of the Realm', '4', 4, 3, 3, 3, 1, 3, '1', 8, 'Cavalry', 14),
    ((SELECT unit_id from units WHERE unit_name ='Knights of the Realm'), 'Gallant', '4', 4, 3, 3, 3, 1, 3, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knights of the Realm'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, '-', 15),
    ((SELECT unit_id from units WHERE unit_name ='Men-at-arms'), 'Men-at-arms', '4', 2, 2, 3, 3, 1, 3, '1', 5, 'Infantry', 199),
    ((SELECT unit_id from units WHERE unit_name ='Men-at-arms'), 'Yeoman Warden', '4', 3, 3, 3, 3, 1, 3, '2', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Peasant Bowmen'), 'Peasant Bowmen', '4', 2, 3, 3, 3, 1, 3, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Peasant Bowmen'), 'Villein', '4', 2, 4, 3, 3, 1, 3, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Questing Knights'), 'Questing Knight', '4', 4, 3, 4, 3, 1, 4, '1', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Questing Knights'), 'Paragon', '4', 4, 3, 4, 3, 1, 4, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Questing Knights'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, '-', 15),
    ((SELECT unit_id from units WHERE unit_name ='Pegasus Knights'), 'Pegasus Knight', '4', 4, 3, 3, 4, 2, 4, '1', 8, 'Cavalry', 9),
    ((SELECT unit_id from units WHERE unit_name ='Pegasus Knights'), 'Gallant', '4', 4, 3, 3, 4, 2, 4, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Pegasus Knights'), 'Pegasus', '8', 3, 0, 4, null, null, 4, '2', 7, '-', 10),
    ((SELECT unit_id from units WHERE unit_name ='Grail Religuae with Battle Pilgrims'), 'Grail Religuae', '4', 2, 2, 3, 3, 6, 3, '', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grail Religuae with Battle Pilgrims'), 'Battle Pilgrim', '4', 2, 2, 3, 3, 1, 3, '1', 8, 'Infantry', 6),
    ((SELECT unit_id from units WHERE unit_name ='Mounted Yeoman'), 'Yeomen', '4', 3, 3, 3, 3, 1, 3, '1', 6, 'Cavalry', 200),
    ((SELECT unit_id from units WHERE unit_name ='Mounted Yeoman'), 'Warden', '4', 3, 3, 3, 3, 1, 3, '2', 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mounted Yeoman'), 'Horse', '8', 3, 0, 3, 3, 1, 3, '1', 5, '-', 200),
    ((SELECT unit_id from units WHERE unit_name ='Grail Knights'), 'Grail Knight', '4', 5, 3, 4, 3, 1, 5, '2', 8, 'Cavalry', 12),
    ((SELECT unit_id from units WHERE unit_name ='Grail Knights'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, '-', 12),
    ((SELECT unit_id from units WHERE unit_name ='Field Trebuchet'), 'Field Trebuchet', null, null, null, null, 7, 4, null, null, null, 'Warmachine', 10),
    ((SELECT unit_id from units WHERE unit_name ='Field Trebuchet'), 'Peasant', '4', 2, 2, 3, 3, 1, 3, '1', 5, 'Warmachine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Field Trebuchet'), 'Yeoman Craftsman', '4', 3, 3, 3, 3, 1, 3, '1', 6, 'Warmachine', 1);
