DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Daemons of Chaos');
DELETE FROM units WHERE faction = 'Daemons of Chaos';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Daemons of Chaos', 'Skarbrand', 'Lords', 610, 1, 1),
    ('Daemons of Chaos', 'Kairos Fateweaver', 'Lords', 565, 1, 1),
    ('Daemons of Chaos', 'Ku´Gath PlagueFather', 'Lords', 625, 1, 1),
    ('Daemons of Chaos', 'Bloodthirster', 'Lords', 400, 1, 1),
    ('Daemons of Chaos', 'Lord of Change', 'Lords', 400, 1, 1),
    ('Daemons of Chaos', 'Great Unclean One', 'Lords', 375, 1, 1),
    ('Daemons of Chaos', 'Keeper of Secrets', 'Lords', 375, 20, 100),
    ('Daemons of Chaos', 'Daemon Prince', 'Lords', 250, 10, 100),
    ('Daemons of Chaos', 'Skulltaker', 'Heroes', 200, 1, 1),
    ('Daemons of Chaos', 'Karanak', 'Heroes', 195, 1, 1),
    ('Daemons of Chaos', 'The Blue Scribes', 'Heroes', 81, 1, 1),
    ('Daemons of Chaos', 'The Changeling', 'Heroes', 170, 1, 1),
    ('Daemons of Chaos', 'Epidemius', 'Heroes', 200, 1, 1),
    ('Daemons of Chaos', 'The Masque of Slaanesh', 'Heroes', 140, 1, 1),
    ('Daemons of Chaos', 'Herald of Khorne', 'Heroes', 100, 1, 1),
    ('Daemons of Chaos', 'Herald of Tzeentch', 'Heroes', 90, 1, 1),
    ('Daemons of Chaos', 'Herald of Nurgle', 'Heroes', 90, 1, 1),
    ('Daemons of Chaos', 'Herald of Slaanesh', 'Heroes', 90, 1, 1),
    ('Daemons of Chaos', 'Bloodletters of Khorne', 'Core', 14, 10, 100),
    ('Daemons of Chaos', 'Pink Horrors of Tzeentch', 'Core', 13, 10, 100),
    ('Daemons of Chaos', 'Plaguebearers of Nurgle', 'Core', 13, 10, 100),
    ('Daemons of Chaos', 'Daemonettes of Slaanesh', 'Core', 11, 10, 100),
    ('Daemons of Chaos', 'Bloodcrushers of Khorne', 'Special', 65, 3, 30),
    ('Daemons of Chaos', 'Flesh Hounds of Khorne', 'Special', 30, 5, 30),
    ('Daemons of Chaos', 'Flamers of Tzeentch', 'Special', 40, 3, 6),
    ('Daemons of Chaos', 'Screamers of Tzeentch', 'Special', 40, 3, 30),
    ('Daemons of Chaos', 'Nurglings', 'Special', 40, 2, 12),
    ('Daemons of Chaos', 'Beasts of Nurgle', 'Special', 60, 1, 10),
    ('Daemons of Chaos', 'Seekers of Slaanesh', 'Special', 20, 5, 50),
    ('Daemons of Chaos', 'Fiends of Slaanesh', 'Special', 65, 3, 30),
    ('Daemons of Chaos', 'Seeker Chariot of Slaanesh', 'Special', 110, 1, 1),
    ('Daemons of Chaos', 'Chaos Furies', 'Special', 12, 5, 50),
    ('Daemons of Chaos', 'Skull Cannon of Khorne', 'Rare', 135, 1, 1),
    ('Daemons of Chaos', 'Burning Chariot of Tzeentch', 'Rare', 150, 1, 1),
    ('Daemons of Chaos', 'Soul Grinder', 'Rare', 250, 1, 1),
    ('Daemons of Chaos', 'Exalted Seeker Chariot of Slaanesh', 'Rare', 220, 1, 1),
    ('Daemons of Chaos', 'Hellflayer of Slaanesh', 'Rare', 130, 1, 1),
    ('Daemons of Chaos', 'Plague Drones of Nurgle', 'Rare', 55, 3, 30);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name ='Skarbrand'), 'Skarbrand', '8', 10, 10, 6, 6, 5, 10, '6', 9, 'Monster(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kairos Fateweaver'), 'Kairos Fateweaver', '8', 1, 0, 5, 5, 5, 1, '1', 9, 'Monster(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ku´Gath PlagueFather'), 'Ku´Gath PlagueFather', '6', 6, 3, 6, 7, 7, 4, '6', 9, 'Monster(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodthirster'), 'Bloodthirster', '8', 10, 10, 6, 6, 5, 9, '6', 9, 'Monster(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lord of Change'), 'Lord of Change', '8', 6, 6, 6, 6, 5, 6, '5', 9, 'Monster(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Great Unclean One'), 'Great Unclean One', '6', 6, 3, 6, 7, 6, 4, '5', 9, 'Monster(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Keeper of Secrets'), 'Keeper of Secrets', '10', 9, 6, 6, 6, 5, 10, '6', 9, 'Monster(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Daemon Prince'), 'Daemon Prince', '8', 9, 5, 6, 5, 4, 8, '5', 9, 'Monster(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skulltaker'), 'Skulltaker', '5', 9, 9, 5, 4, 2, 9, '4', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Karanak'), 'Karanak', '8', 7, 0, 5, 5, 3, 6, '4', 8, 'War Beast(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Blue Scribes'), 'The Blue Scribes', null, 3, 3, 3, 3, 2, 3, '2', 7, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Blue Scribes'), 'Disc of Tzeentch', '1', 3, 0, 4, 4, 1, 4, '3', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='The Changeling'), 'The Changeling', '4', 3, 4, 3, 3, 2, 3, '1', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Epidemius'), 'Epidemius', null, 5, 5, 5, 5, 2, 4, '3', 8, 'Monstrous Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Epidemius'), 'Palanquin of Nurgle', '4', 3, 3, 3, 3, 4, 3, '6', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='The Masque of Slaanesh'), 'The Masque of Slaanesh', '10', 7, 6, 4, 3, 2, 7, '5', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Herald of Khorne'), 'Herald of Khorne', '5', 7, 7, 5, 4, 2, 6, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Herald of Tzeentch'), 'Herald of Tzeentch', '4', 3, 4, 3, 3, 2, 3, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Herald of Nurgle'), 'Herald of Nurgle', '4', 5, 5, 5, 5, 2, 4, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Herald of Slaanesh'), 'Herald of Slaanesh', '6', 7, 6, 4, 3, 2, 7, '4', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodletters of Khorne'), 'Bloodletter', '5', 5, 5, 4, 3, 1, 4, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Bloodletters of Khorne'), 'Bloodreaper', '5', 5, 5, 4, 3, 1, 4, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Pink Horrors of Tzeentch'), 'Pink Horror', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Pink Horrors of Tzeentch'), 'Iridescent Horror', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plaguebearers of Nurgle'), 'Plaguebearer', '4', 3, 3, 4, 4, 1, 2, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Plaguebearers of Nurgle'), 'Plagueridden', '4', 3, 3, 4, 4, 1, 2, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Daemonettes of Slaanesh'), 'Daemonette', '6', 5, 4, 3, 3, 1, 5, '2', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Daemonettes of Slaanesh'), 'Alluress', '6', 5, 4, 3, 3, 1, 5, '3', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodcrushers of Khorne'), 'Bloodletter', '5', 5, 5, 4, 3, 1, 4, '1', 7, 'Monstrous Cavalry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Bloodcrushers of Khorne'), 'Bloodhunter', '5', 5, 5, 4, 3, 1, 4, '2', 7, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bloodcrushers of Khorne'), 'Juggernaut of Khorne', '7', 5, 0, 5, 4, 3, 2, '3', 7, null, 30),
    ((SELECT unit_id from units WHERE unit_name ='Flesh Hounds of Khorne'), 'Flesh Hound', 8, 5, 0, 4, 4, 2, 4, 2, 7, 'War Beast', 50),
    ((SELECT unit_id from units WHERE unit_name ='Flamers of Tzeentch'), 'Flamer', '6', 2, 4, 4, 4, 2, 4, '2', 7, 'Infantry', 6),
    ((SELECT unit_id from units WHERE unit_name ='Flamers of Tzeentch'), 'Pyrocaster', 6, 2, 5, 4, 4, 2, 4, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Screamers of Tzeentch'), 'Screamer', '1', 3, 0, 4, 4, 2, 4, '3', 7, 'War Beast', 30),
    ((SELECT unit_id from units WHERE unit_name ='Nurglings'), 'Nurglings', '4', 3, 3, 3, 3, 4, 3, 4, 7, 'Swarm', 1),
    ((SELECT unit_id from units WHERE unit_name ='Beasts of Nurgle'), 'Beasts of Nurgle', 6, 3, 0, 4, 5, 4, 2, 'D6+1', 7, 'Monstrous Beast', 10),
    ((SELECT unit_id from units WHERE unit_name ='Seekers of Slaanesh'), 'Seeker', '6', 5, 4, 3, 3, 1, 5, '2', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Seekers of Slaanesh'), 'Heartseeker', '6', 5, 4, 3, 3, 1, 5, '3', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Seekers of Slaanesh'), 'Steed of Slaanesh', '10', 3, 0, 3, 3, 1, 5, '1', 7, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Fiends of Slaanesh'), 'Fiend of Slaanesh', '10', 4, 0, 4, 4, 3, 6, '3', 7, 'Monstrous Beast', 30),
    ((SELECT unit_id from units WHERE unit_name ='Seeker Chariot of Slaanesh'), 'Seeker Chariot', null, null, null, 4, 4, 4, null, null, null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Seeker Chariot of Slaanesh'), 'Daemonette Crew', null, 5, 4, 3, null, null, 5, '2', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Seeker Chariot of Slaanesh'), 'Steed of Slaanesh', '10', 3, 0, 3, null, null, 5, '1', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Chaos Furies'), 'Chaos Fury', '4', 3, 0, 4, 3, 1, 4, '1', 2, 'Infantry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Skull Cannon of Khorne'), 'Skull Cannon', '7', 5, null, 5, 5, 4, 2, '3', null, 'Chariot(Armour Save 3+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skull Cannon of Khorne'), 'Bloodletter Crew', null, 5, 5, 4, null, null, 4, 1, 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Burning Chariot of Tzeentch'), 'Burning Chariot', null, null, null, 4, 4, 4, null, null, null, 'Chariot(Armour Save -)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Burning Chariot of Tzeentch'), 'Exalted Flamer', null, 4, 4, 4, null, null, 4, '3', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Burning Chariot of Tzeentch'), 'Screamer', '1', 3, 0, 4, null, null, 4, '3', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Soul Grinder'), 'Soul Grinder', '8', 3, 3, 6, 7, 6, 3, 4, 7, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Exalted Seeker Chariot of Slaanesh'), 'Exalted Chariot', null, null, null, 4, 4, 8, null, null, null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Exalted Seeker Chariot of Slaanesh'), 'Exalted Alluress', null, 5, 4, 3, null, null, 5, '4', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Exalted Seeker Chariot of Slaanesh'), 'Daemonette Crew', null, 5, 4, 3, null, null, 5, '2', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Exalted Seeker Chariot of Slaanesh'), 'Steed of Slaanesh', '10', 3, 0, 3, null, null, 5, '1', null, null, 4),
    ((SELECT unit_id from units WHERE unit_name ='Hellflayer of Slaanesh'), 'Hellflayer', null, null, null, 4, 4, 4, null, null, null, 'Chariot(Armour Save 6+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hellflayer of Slaanesh'), 'Exalted Alluress', null, 5, 4, 3, null, null, 5, '2', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Hellflayer of Slaanesh'), 'Daemonette Crew', null, 5, 4, 3, null, null, 5, '2', 7, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Hellflayer of Slaanesh'), 'Steed of Slaanesh', '10', 3, 0, 3, null, null, 5, '1', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Plague Drones of Nurgle'), 'Plaguebearer', '4', 3, 3, 4, 4, 1, 2, '1', 7, 'Monstrous Cavalry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Plague Drones of Nurgle'), 'Plaguebringer', '4', 3, 3, 4, 4, 1, 2, '2', 7, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Plague Drones of Nurgle'), 'Rot Fly', '1', 3, 3, 5, 5, 3, 2, '3', 7, null, 30);
