DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Ogre Kingdoms');
DELETE FROM units WHERE faction = 'Ogre Kingdoms';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Ogre Kingdoms', 'Greasus Goldtooth', 'Lords', 545, 1, 1),
    ('Ogre Kingdoms', 'Skrag the Slaughterer', 'Lords', 425, 1, 1),
    ('Ogre Kingdoms', 'Tyrant' ,'Lords' , 210, 1, 1),
    ('Ogre Kingdoms', 'Slaughtermaster','Lords' , 250, 1, 1),
    ('Ogre Kingdoms', 'Golgfag Maneater','Heroes' , 260, 1, 1),
    ('Ogre Kingdoms', 'Bragg the Gutsman','Heroes' , 210, 1, 1),
    ('Ogre Kingdoms', 'Bruiser','Heroes' , 105, 1, 1),
    ('Ogre Kingdoms', 'Hunter' ,'Heroes' , 130, 1, 1),
    ('Ogre Kingdoms', 'Butcher','Heroes' , 100, 1, 1),
    ('Ogre Kingdoms', 'Firebelly','Heroes' , 120, 1, 1),
    ('Ogre Kingdoms', 'Ogres' ,'Core' , 30, 3, 30),
    ('Ogre Kingdoms', 'Ironguts','Core' , 43, 3, 30),
    ('Ogre Kingdoms', 'Gnoblars','Core' , 2.5, 10, 100),
    ('Ogre Kingdoms', 'Leadbelchers','Special' , 43, 3, 30),
    ('Ogre Kingdoms', 'Maneaters','Special' , 50, 3, 30),
    ('Ogre Kingdoms', 'Sabretusk Pack','Special' , 21, 1, 10),
    ('Ogre Kingdoms', 'Yhetees','Special' , 44, 3, 30),
    ('Ogre Kingdoms', 'Mournfang Cavalry','Special' , 60, 2, 20),
    ('Ogre Kingdoms', 'Gorger','Special' , 90, 1, 1),
    ('Ogre Kingdoms', 'Gnoblar Scraplauncher','Rare' , 130, 1, 1),
    ('Ogre Kingdoms', 'Ironblaster','Rare' , 170, 1, 1),
    ('Ogre Kingdoms', 'Giant','Rare' , 200, 1, 1),
    ('Ogre Kingdoms', 'Stonehorn','Rare' , 250, 1, 1),
    ('Ogre Kingdoms', 'Thundertusk','Rare' , 250, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Greasus Goldtooth'), 'Greasus Goldtooth', '4', 6, 3, 5, 6, 6, 1, '3', 9, 'Monstrous Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Skrag the Slaughterer'), 'Skrag the Slaughterer', '6', 5, 3, 5, 6, 5, 3, '4', 9, 'Monstrous Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tyrant'), 'Tyrant', '6', 6, 4, 5, 5, 5, 4, '5', 9, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Slaughtermaster'), 'Slaughtermaster', '6', 4, 3, 4, 5, 5, 3, '4', 8, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Golgfag Maneater'), 'Golgfag Maneater', '6', 5, 4, 5, 5, 4, 4, '5', 8, 'Monstrous Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bragg the Gutsman'), 'Bragg the Gutsman', '6', 5, 3, 6, 5, 4, 3, '4', 8, 'Monstrous Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bruiser'), 'Bruiser', '6', 5, 3, 5, 5, 4, 3, '4', 8, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hunter'), 'Hunter', '6', 5, 4, 5, 5, 4, 3, '4', 9, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Butcher'), 'Butcher', '6', 3, 2, 4, 5, 4, 2, '3', 7, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Firebelly'), 'Firebelly', '6', 3, 2, 4, 5, 4, 2, '3', 7, 'Monstrous Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ogres' AND faction = 'Ogre Kingdoms'), 'Ogre', '6', 3, 2, 4, 4, 3, 2, '3', 7, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Ogres' AND faction = 'Ogre Kingdoms'), 'Crusher', '6', 3, 2, 4, 4, 3, 2, '4', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ironguts'), 'Irongut', '6', 3, 2, 4, 4, 3, 2, '3', 8, 'Monstrous Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Ironguts'), 'Gutlord', '6', 3, 2, 4, 4, 3, 2, '4', 8, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gnoblars'), 'Gnoblar', '4', 2, 3, 2, 3, 1, 3, '1', 5, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Gnoblars'), 'Groinbiter', '4', 2, 3, 2, 3, 1, 3, '2', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Leadbelchers'), 'Leadbelcher', '6', 3, 3, 4, 4, 3, 2, '3', 7, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Leadbelchers'), 'Thunderfist', '6', 3, 3, 4, 4, 3, 2, '4', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Maneaters'), 'Maneater', '6', 4, 4, 5, 4, 3, 3, '4', 8, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Maneaters'), 'Maneater Captain', '6', 4, 4, 5, 4, 3, 3, '5', 8, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Sabretusk Pack'), 'Sabretusk', '8', 4, 0, 4, 4, 2, 4, '3', 4, 'War Beast', 10),
    ((SELECT unit_id from units WHERE unit_name ='Yhetees'), 'Yhetee', '7', 3, 0, 5, 4, 3, 4, '3', 7, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Yhetees'), 'Greyback', '7', 3, 0, 5, 4, 3, 4, '4', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mournfang Cavalry'), 'Ogre', '6', 3, 2, 4, 4, 3, 2, '3', 7, 'Monstrous Cavalry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Mournfang Cavalry'), 'Crusher', '6', 3, 2, 4, 4, 3, 2, '4', 7, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mournfang Cavalry'), 'Mournfang', '8', 3, 0, 5, 4, 3, 2, '4', 5, null, 20),
    ((SELECT unit_id from units WHERE unit_name ='Gorger'), 'Gorger', 6, 3, 0, 5, 5, 4, 2, '4', 8, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gnoblar Scraplauncher'), 'Scraplauncher', null, null, null, 5, 5, 5, null, null, null, 'Chariot(Armour Save 4+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Gnoblar Scraplauncher'), 'Gnoblar Scrapper', null, 2, 3, 2, null, null, 3, '1', 5, null, 7),
    ((SELECT unit_id from units WHERE unit_name ='Gnoblar Scraplauncher'), 'Rhinox', '6', 3, null, 5, null, null, 2, '3', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Ironblaster'), 'Ironblaster', null, null, null, 5, 6, 5, null, null, null, 'Chariot(Armour Save 4+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ironblaster'), 'Leadbelcher', null, 3, 3, 4, null, null, 2, '3', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Ironblaster'), 'Gnoblar Scrapper', null, 2, 3, 2, null, null, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Ironblaster'), 'Rhinox', '6', 3, null, 5, null, null, 2, '3', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Giant' AND faction = 'Ogre Kingdoms'), 'Giant', '6', 3, 3, 6, 5, 6, 3, 'special', 10, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Stonehorn'), 'Stonehorn', '7', 3, 0, 6, 6, 6, 2, '5', 5, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Stonehorn'), 'Ogre Beast Rider', null, 3, 3, 4, null, null, 2, '3', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Thundertusk'), 'Thundertusk', '6', 3, 0, 6, 6, 6, 2, '4', 5, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Thundertusk'), 'Ogre Beast Rider', null, 3, 3, 4, null, null, 2, '3', 7, null, 2);
