DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Vampire Counts');
DELETE FROM units WHERE faction = 'Vampire Counts';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Vampire Counts', 'Vlad Von Carstein' ,'Lords' , 495, 1, 1),
    ('Vampire Counts', 'Count Mannfred','Lords' , 530, 1, 1),
    ('Vampire Counts', 'Heinrich Kemmler','Lords' , 350, 1, 1),
    ('Vampire Counts', 'Vampire Lord','Lords' , 220, 1, 1),
    ('Vampire Counts', 'Master Necromancer','Lords' , 165, 1, 1),
    ('Vampire Counts', 'Strigoi Ghoul King' ,'Lords' , 260, 1, 1),
    ('Vampire Counts', 'Mannfred the Acolyte' ,'Heroes' , 200, 1, 1),
    ('Vampire Counts', 'Krell, Lord of Undeath','Heroes' , 205, 1, 1),
    ('Vampire Counts', 'Konrad Von Carstein','Heroes' , 160, 1, 1),
    ('Vampire Counts', 'Isabella Von Carstein','Heroes' , 175, 1, 1),
    ('Vampire Counts', 'Necromancer','Heroes' , 65, 1, 1),
    ('Vampire Counts', 'Vampire','Heroes' , 105, 1, 1),
    ('Vampire Counts', 'Wight King','Heroes' , 85, 1, 1),
    ('Vampire Counts', 'Cairn Wraith','Heroes' , 60, 1, 1),
    ('Vampire Counts', 'Tomb Banshee','Heroes' , 95, 1, 1),
    ('Vampire Counts', 'Zombies' ,'Core' , 3, 20, 200),
    ('Vampire Counts', 'Skeleton Warriors','Core' , 5, 10, 100),
    ('Vampire Counts', 'Crypt Ghouls','Core' , 10, 10, 100),
    ('Vampire Counts', 'Dire Wolves','Core' , 8, 5, 20),
    ('Vampire Counts', 'Corpse Cart','Special' , 90, 1, 1),
    ('Vampire Counts', 'Grave Guard','Special' , 11, 10, 100),
    ('Vampire Counts', 'Black Knights','Special' , 21, 5, 50),
    ('Vampire Counts', 'Crypt Horrors','Special' , 38, 3, 30),
    ('Vampire Counts', 'Fell Bats','Special' , 16, 2, 20),
    ('Vampire Counts', 'Bat Swarms','Special' , 35, 2, 20),
    ('Vampire Counts', 'Spirit Host','Special' , 45, 1, 10),
    ('Vampire Counts', 'Hex Wraiths','Special' , 30, 5, 10),
    ('Vampire Counts', 'Vargheists','Special' , 46, 3, 30),
    ('Vampire Counts', 'Varghulf','Rare' , 175, 1, 1),
    ('Vampire Counts', 'Blood Knights','Rare' , 50, 4, 40),
    ('Vampire Counts', 'Cairn Wraiths','Rare' , 50, 3, 10),
    ('Vampire Counts', 'Black Coach','Rare' , 195, 1, 1),
    ('Vampire Counts', 'Terrorgheist','Rare' , 225, 1, 1),
    ('Vampire Counts', 'Mortis Engine','Rare' , 220, 1, 1);


INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Vlad Von Carstein'), 'Vlad Von Carstein', '6', 7, 5, 5, 5, 3, 7, '5', 10, 'Infantry(Special Character, Vampire Lord)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Count Mannfred'), 'Count Mannfred', '6', 7, 5, 5, 5, 5, 7, '5', 10, 'Infantry(Special Character, Vampire Lord)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Heinrich Kemmler'), 'Heinrich Kemmler', '4', 4, 3, 4, 4, 3, 4, '1', 9, 'Infantry(Special Character, Master Necromancer)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Vampire Lord'), 'Vampire Lord', '6', 7, 5, 5, 5, 3, 7, '5', 10, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Master Necromancer'), 'Master Necromancer', '4', 3, 3, 3, 4, 3, 3, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Strigoi Ghoul King'), 'Strigoi Ghoul King', '6', 6, 3, 5, 5, 3, 8, '5', 9, 'Infantry(Character, Vampire)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mannfred the Acolyte'), 'Mannfred the Acolyte', '6', 6, 4, 5, 4, 2, 6, '4', 7, 'Infantry(Special Character, Vampire)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Krell, Lord of Undeath'), 'Krell', '4', 5, 0, 4, 5, 4, 5, '3', 9, 'Infantry(Special Character, Wight King)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Konrad Von Carstein'), 'Konrad Von Carstein', '6', 7, 4, 5, 4, 2, 6, '4', 6, 'Infantry(Special Character, Vampire)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Isabella Von Carstein'), 'Isabella Von Carstein', '6', 6, 4, 5, 4, 2, 6, '4', 7, 'Infantry(Special Character, Vampire)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Necromancer'), 'Necromancer', '4', 3, 3, 3, 3, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Vampire'), 'Vampire', '6', 6, 4, 5, 4, 2, 6, '4', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Wight King'), 'Wight King', '4', 4, 0, 4, 5, 3, 4, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cairn Wraith'), 'Cairn Wraith', '6', 3, 0, 3, 3, 2, 2, '3', 5, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tomb Banshee'), 'Tomb Banshee', '6', 3, 0, 3, 3, 2, 3, '1', 5, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Zombies'), 'Zombie', '4', 1, 0, 3, 3, 1, 1, '1', 2, 'Infantry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Skeleton Warriors ' AND faction = 'Vampire Counts'), 'Skeleton Warrior', '4', 2, 2, 3, 3, 1, 2, '1', 3, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Skeleton Warriors' AND faction = 'Vampire Counts'), 'Skeleton Champion', '4', 2, 2, 3, 3, 1, 2, '2', 3, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Crypt Ghouls'), 'Crypt Ghouls', '4', 3, 0, 3, 4, 1, 3, '2', 5, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Crypt Ghouls'), 'Crypt Ghast', '4', 3, 0, 3, 4, 1, 3, '3', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dire Wolves'), 'Dire Wolf', '9', 3, 0, 3, 3, 1, 3, '1', 3, 'War Beasts', 20),
    ((SELECT unit_id from units WHERE unit_name ='Dire Wolves'), 'Doom Wolf', '9', 3, 0, 3, 3, 1, 3, '2', 3, 'War Beasts', 1),
    ((SELECT unit_id from units WHERE unit_name ='Corpse Cart'), 'Corpse Cart', null, null, null, 4, 4, 4, null, null, null, 'Chariot(Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Corpse Cart'), 'Corpsemaster', null, 3, 0, 3, null, null, 2, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Corpse Cart'), 'The Restless Dead', '4', 1, null, 3, null, null, 1, '2D6*', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Grave Guard'), 'Grave Guard', '4', 3, 0, 4, 4, 1, 3, '1', 6, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Grave Guard'), 'Seneschal', '4', 3, 0, 4, 4, 1, 3, '2', 6, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Knights'), 'Black Knight', '4', 3, 0, 4, 4, 1, 3, '1', 6, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Black Knights'), 'Hell Knight', '4', 3, 0, 4, 4, 1, 3, '2', 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Knights'), 'Skeletal Steed', '8', 2, 0, 3, 3, 1, 2, '1', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Crypt Horrors'), 'Crypt Horror', '6', 3, 0, 4, 5, 3, 2, '3', 5, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Crypt Horrors'), 'Crypt Haunter', '6', 3, 0, 4, 5, 3, 2, '4', 5, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Fell Bats'), 'Fell Bats', '1', 3, 0, 3, 3, 2, 3, '2', 3, 'War Beast', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bat Swarms'), 'Bat Swarms', '1', 3, 0, 2, 2, 5, 4, '5', 3, 'Swarm', 2),
    ((SELECT unit_id from units WHERE unit_name ='Spirit Host'), 'Spirit Host', '6', 3, 0, 3, 3, 4, 1, '4', 4, 'Swarm', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hexwraiths'), 'Hexwraith', '6', 3, 0, 3, 3, 1, 2, '1', 5, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hexwraiths'), 'Hellwraith','6', 3, 0, 3, 3, 1, 2, '2', 5, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hexwraiths'), 'Skeletal Steed', '8', 2, 0, 3, 3, 1, 2, '1', 3, null, 10),
    ((SELECT unit_id from units WHERE unit_name ='Vargheists'), 'Vargheist', '6', 4, 0, 5, 4, 3, 4, '3', 7, 'Monstrous Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Vargheists'), 'Vargoyle', '6', 4, 0, 5, 4, 3, 4, '4', 7, 'Monstrous Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Varghulf'), 'Varghulf', '8', 5, 0, 5, 5, 4, 4, '5', 4, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Blood Knights'), 'Blood Knight', '4', 5, 3, 5, 4, 1, 5, '2', 7, 'Cavalry', 40),
    ((SELECT unit_id from units WHERE unit_name ='Blood Knights'), 'Kastellan', '4', 5, 3, 5, 4, 1, 5, '3', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Blood Knights'), 'Nightmare', '8', 3, 0, 4, 4, 1, 2, '1', 3, null, 40),
    ((SELECT unit_id from units WHERE unit_name ='Cairn Wraiths'), 'Cairn Wraith', '6', 3, 0, 3, 3, 2, 2, '3', 5, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Cairn Wraiths'), 'Tomb Banshee', '6', 3, 0, 3, 3, 2, 3, '1', 5, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Coach'), 'Black Coach', null, null, null, 5, 6, 4, null, null, null, 'Chariot(Armour Save 3+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Coach'), 'Cairn Wraith', null, 3, 0, 3, null, null, 2, '3', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Black Coach'), 'Nightmare', '8', 3, 0, 4, null, null, 2, '1', null, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Terrorgheist'), 'Terrorgheist', '6', 3, 0, 5, 6, 6, 3, '4', 4, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortis Engine'), 'Mortis Engine', null, null, null, 5, 5, 5, null, null, null, 'Chariot(Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortis Engine'), 'Corpsemaster', null, 3, 0, 3, null, null, 2, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortis Engine'), 'Banshee Swarm', null, 3, 0, 3, null, null, 3, '3', null, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortis Engine'), 'Spirit Horde', '8', 3, 0, 3, null, null, 1, '2D6*', null, null, 1);

