DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'Dogs of War');
DELETE FROM units WHERE faction = 'Dogs of War';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('Dogs of War', 'Mercenary General' ,'Lords' , 90, 1, 1),
    ('Dogs of War', 'Hireling Wizard Lord' ,'Lords' , 175, 1, 1),
    ('Dogs of War', 'Paymaster','Heroes' , 55, 1, 1),
    ('Dogs of War', 'Mercenary Captain' ,'Heroes' , 50, 1, 1),
    ('Dogs of War', 'Hireling Wizard','Heroes' , 60, 1, 1),
    ('Dogs of War', 'Pikemen' ,'Core' , 10, 10, 100),
    ('Dogs of War', 'Crossbowmen','Core' , 8, 10, 100),
    ('Dogs of War', 'Duellists','Core' , 5, 8, 80),
    ('Dogs of War', 'Heavy Cavalry','Core' , 19, 5, 50),
    ('Dogs of War', 'Light Cavalry','Core' , 11, 5, 50),
    ('Dogs of War', 'Vespero´s Vendetta','Core' , 125, 5, 50),
    ('Dogs of War', 'Pirazzo´s Lost Legion', 'Core' , 160, 10, 100 ),
    ('Dogs of War', 'Ricco´s Republican Guard', 'Core' , 180, 10, 100),
    ('Dogs of War', 'Voland´s Venators', 'Core' , 195, 5, 50),
    ('Dogs of War', 'The Alcatani Fellowship', 'Core' , 125, 10, 100),
    ('Dogs of War', 'Marksmen of Miragliano', 'Core' , 180, 10, 100),
    ('Dogs of War', 'Al Muktar´s Desert Dogs', 'Core' , 245, 5, 50),
    ('Dogs of War', 'Leopold´s Leopard Company', 'Core' , 210, 10, 100),
    ('Dogs of War', 'Braganza´s Besiegers', 'Core' , 195, 10, 100),
    ('Dogs of War', 'Ogres','Special' , 35, 3, 30),
    ('Dogs of War', 'Dwarfs','Special' , 7, 10, 100),
    ('Dogs of War', 'Norse Marauders','Special' , 7, 10, 100),
    ('Dogs of War', 'Paymaster´s Bodyguard','Special' , 9, 10, 100),
    ('Dogs of War', 'Halflings','Special' , 6, 10, 100),
    ('Dogs of War', 'Beorg Bearstruck and the Bearmen of Urslo', 'Special' , 255 , 10 ,100),
    ('Dogs of War', 'Oglah Khan´s Wolfboyz', 'Special', 190 , 6, 60),
    ('Dogs of War', 'Lumpin Croop´s Fighting Cocks', 'Special', 190 , 6, 60),
    ('Dogs of War', 'Golgfag´s Ogres', 'Special', 285 , 4, 40),
    ('Dogs of War', 'Long Drong´s Slayer Pirates', 'Special', 195 , 10, 100),
    ('Dogs of War', 'Cannons','Rare' , 85, 1, 3),
    ('Dogs of War', 'Halfling Hot Pot','Rare' , 50, 1, 1),
    ('Dogs of War', 'Giants of Albion', 'Rare' , 450, 1, 1),
    ('Dogs of War', 'Asarnil the Dragonlord', 'Rare' , 460, 1, 1),
    ('Dogs of War', 'Tichi Huichi´s Raiders', 'Rare' , 250, 6, 60),
    ('Dogs of War', 'Birdmen of Catrazza', 'Rare' , 150, 5, 10),
    ('Dogs of War', 'Bronzino´s Galloper Guns', 'Rare' , 165, 2, 5);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Mercenary General'), 'General', '4', 6, 5, 4, 4, 3, 6, '4', 9, 'Special Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mercenary General'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mercenary General'), 'Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 6, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Hireling Wizard Lord'), 'Wizard Lord', '4', 3, 3, 3, 4, 3, 3, '1', 8, 'Special Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hireling Wizard Lord'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Hireling Wizard Lord'), 'Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 6, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Paymaster'), 'Paymaster', '4', 4, 4, 4, 4, 2, 4, '2', 8, 'Special Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paymaster'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mercenary Captain'), 'Captain', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Special Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mercenary Captain'),  'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mercenary Captain'), 'Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 6, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Hireling Wizard'), 'Hireling Wizard', '4', 3, 3, 3, 3, 2, 3, '1', 7, 'Special Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Hireling Wizard'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Pikemen'), 'Pikemen', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Crossbowmen' AND faction = 'Dogs of War'), 'Crossbowmen', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Duellists'), 'Duellists', '4', 4, 3, 3, 3, 1, 4, '1', 7, 'Infantry', 80),
    ((SELECT unit_id from units WHERE unit_name ='Heavy Cavalry'), 'Knight', '4', 4, 3, 3, 3, 1, 3, '1', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Heavy Cavalry'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Light Cavalry'), 'Horsemen', '4', 3, 3, 3, 3, 1, 4, '1', 7, 'Cavalry', 80),
    ((SELECT unit_id from units WHERE unit_name ='Light Cavalry'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Vespero´s Vendetta'), 'Vespero', '4', 6, 5, 4, 4, 2, 6, '3', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Vespero´s Vendetta'), 'Duellists', '4', 4, 3, 3, 3, 1, 4, '1', 7, 'Infantry', 40),
    ((SELECT unit_id from units WHERE unit_name ='Pirazzo´s Lost Legion'), 'Pirazzo', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Pirazzo´s Lost Legion'), 'Crossbow', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Pirazzo´s Lost Legion'), 'Pike', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Ricco´s Republican Guard'), 'Ricco', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ricco´s Republican Guard'), 'Pikemen', '4', 4, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Voland´s Venators'), 'Voland', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Voland´s Venators'), 'Venators', '4', 4, 3, 4, 3, 1, 3, '1', 8, 'Cavalry', 4),
    ((SELECT unit_id from units WHERE unit_name ='Voland´s Venators'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='The Alcatani Fellowship'), 'Roderigo', '4', 4, 4, 4, 3, 2, 4, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='The Alcatani Fellowship'), 'Pikemen', '4', 2, 2, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Marksmen of Miragliano'), 'Maximilian', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Marksmen of Miragliano'), 'Marksmen', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Al Muktar´s Desert Dogs'), 'Al Muktar', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Al Muktar´s Desert Dogs'), 'Sheikh Shufti', '4', 4, 4, 4, 3, 2, 4, '2', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Al Muktar´s Desert Dogs'), 'Ibn', '4', 3, 3, 3, 3, 1, 3, '0', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Al Muktar´s Desert Dogs'), 'Rider', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Al Muktar´s Desert Dogs'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Leopold´s Leopard Company'), 'Leopold', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Leopold´s Leopard Company'), 'Pikemen', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Braganza´s Besiegers'), 'Braganza', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Braganza´s Besiegers'), 'Besiegers', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Ogres' AND faction = 'Dogs of War'), 'Ogre', '6', 3, 2, 4, 4, 3, 2, '3', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Dwarfs'), 'Dwarf', '3', 4, 3, 3, 4, 1, 2, '1', 9, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Norse Marauders'), 'Marauder', '4', 4, 3, 3, 3, 1, 4, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Paymaster´s Bodyguard'), 'Bodyguard', '4', 4, 3, 3, 3, 1, 3, '1', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Halflings'), 'Halfling', '4', 2, 4, 2, 2, 1, 5, '1', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Beorg Bearstruck and the Bearmen of Urslo'), 'Beorg', '4', 5, 0, 5, 5, 3, 3, '4', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Beorg Bearstruck and the Bearmen of Urslo'), 'Oerl', '4', 4, 3, 3, 3, 1, 4, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Beorg Bearstruck and the Bearmen of Urslo'), 'Bearman', '4', 4, 3, 3, 3, 1, 4, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Oglah Khan´s Wolfboyz'), 'Oglah Khan', '4', 5, 4, 4, 4, 2, 3, '3', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Oglah Khan´s Wolfboyz'), 'Hobgoblin', '4', 3, 3, 3, 3, 1, 2, '1', 6, 'Cavalry', 5),
    ((SELECT unit_id from units WHERE unit_name ='Oglah Khan´s Wolfboyz'), 'Giant Wolf', '9', 3, 0, 3, 3, 1, 3, '1', 3, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Lumpin Croop´s Fighting Cocks'), 'Lumpin Croop', '4', 3, 5, 3, 3, 2, 6, '2', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lumpin Croop´s Fighting Cocks'), 'Ned Hamfist', '4', 2, 5, 2, 2, 1, 5, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Lumpin Croop´s Fighting Cocks'), 'Halfling', '4', 2, 4, 2, 2, 1, 5, '1', 8, 'Infantry', 20),
    ((SELECT unit_id from units WHERE unit_name ='Golgfag´s Ogres'), 'Golgfag', '6', 5, 2, 5, 5, 4, 3, '5', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Golgfag´s Ogres'), 'Skaff', '6', 3, 2, 4, 4, 3, 2, '4', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Golgfag´s Ogres'), 'Ogre', '6', 3, 2, 4, 4, 3, 2, '3', 7, 'Infantry', 40),
    ((SELECT unit_id from units WHERE unit_name ='Long Drong´s Slayer Pirates'), 'Drong', '3', 6, 4, 4, 4, 2, 4, '3', 10, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Long Drong´s Slayer Pirates'), 'Pirates', '3', 4, 3, 3, 4, 1, 3, '1', 9, 'Infantry', 30),
    ((SELECT unit_id from units WHERE unit_name ='Cannons'), 'Cannon', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Cannons'), 'Crew', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Halfling Hot Pot'), 'Hot Pot', null, null, null, null, 4, 2, null, null, null, 'War Machine(Stone Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Halfling Hot Pot'), 'Crew', '4', 2, 4, 2, 2, 1, 5, '1', 8, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Giants of Albion'), 'Hengus', '4', 3, 3, 3, 3, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Giants of Albion'), 'Bologs', '6', 3, 3, 6, 5, 5, 3, 'special', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Giants of Albion'), 'Cachtorr', '6', 3, 3, 6, 5, 5, 3, 'special', 6, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Asarnil the Dragonlord'), 'Asarnil', '5', 7, 4, 4, 3, 2, 7, '4', 9, 'Infantry(Character', 1),
    ((SELECT unit_id from units WHERE unit_name ='Asarnil the Dragonlord'), 'Deathfang', '6', 6, 0, 6, 6, 6, 3, '5', 8, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tichi Huichi´s Raiders'), 'Tichi-Huichi', '6', 4, 4, 4, 3, 2, 5, '3', 7, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tichi Huichi´s Raiders'), 'Gt.Crested Skink', '6', 2, 3, 3, 2, 1, 4, '1', 6, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Tichi Huichi´s Raiders'), 'Cold One', '8', 3, 0, 4, 4, 1, 1, '2', 3, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Birdmen of Catrazza'), 'Daddallo', '4', 4, 4, 3, 3, 2, 3, '1', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Birdmen of Catrazza'), 'Birdmen', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bronzino´s Galloper Guns'), 'Bronzino', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Bronzino´s Galloper Guns'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Bronzino´s Galloper Guns'), 'Crew', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Bronzino´s Galloper Guns'), 'Gun', '8', null, null, null, 6, 2, null, null, null, 'War Machine', 1);




