DELETE FROM profiles WHERE unit_id IN(SELECT unit_id FROM units WHERE faction = 'The Empire');
DELETE FROM units WHERE faction = 'The Empire';

INSERT INTO units (faction, unit_name, type, points_per_model, unit_size_min, unit_size_max) VALUES
    ('The Empire', 'Karl Franz, The Emperor' ,'Lords' , 340, 1, 1),
    ('The Empire', 'Kurt Helborg, Reiksmarshal of the Empire','Lords' , 320, 1, 1),
    ('The Empire', 'Balthasar Gelt, The Supreme Patriarch','Lords' , 360, 1, 1),
    ('The Empire', 'Volkmar the Grim, The Grand Theogonist','Lords' , 190, 1, 1),
    ('The Empire', 'Marius Leitdorf','Lords' , 220, 1, 1),
    ('The Empire', 'General of the Empire' ,'Lords' , 95, 1, 1),
    ('The Empire', 'Battle Wizard Lord','Lords' , 165, 1, 1),
    ('The Empire', 'Arch Lector','Lords' , 100, 1, 1),
    ('The Empire', 'Grand Master','Lords' , 155, 1, 1),
    ('The Empire', 'Ludwig Schwarzhelm, The Emperor`s Champion','Heroes' , 185, 1, 1),
    ('The Empire', 'Luthor Huss, Prophet of Sigmar','Heroes' , 155, 1, 1),
    ('The Empire', 'Markus Wulfhart, Huntsmarshal of the Empire','Heroes' , 140, 1, 1),
    ('The Empire', 'Captain of the Empire','Heroes' , 60, 1, 1),
    ('The Empire', 'Battle Wizard','Heroes' , 65, 1, 1),
    ('The Empire', 'Warrior Priest','Heroes' , 65, 1, 1),
    ('The Empire', 'Master Engineer' ,'Heroes' , 65, 1, 1),
    ('The Empire', 'Witch Hunter','Heroes' , 50, 1, 1),
    ('The Empire', 'Halberdiers','Core' , 6, 10, 100),
    ('The Empire', 'Spearmen','Core' , 5, 10, 100),
    ('The Empire', 'Swordsmen','Core' , 7, 10, 100),
    ('The Empire', 'Crossbowmen','Core' , 9, 10, 100),
    ('The Empire', 'Handgunners','Core' , 9, 10, 100),
    ('The Empire', 'Archers','Core' , 7, 10, 100),
    ('The Empire', 'Free Company Militia','Core' , 6, 10, 100),
    ('The Empire', 'Knightly Orders','Core' , 22, 5, 50),
    ('The Empire', 'Greatswords' ,'Special' , 11, 10, 100),
    ('The Empire', 'Demigryph Knights' ,'Special' , 58, 3, 30),
    ('The Empire', 'Reiksguard Knights','Special' , 27, 5, 50),
    ('The Empire', 'Huntsmen','Special' , 8, 10, 100),
    ('The Empire', 'Pistoliers','Special' , 18, 5, 50),
    ('The Empire', 'Outriders','Special' , 21, 5, 50),
    ('The Empire', 'Great Cannon','Special' , 120, 1, 1),
    ('The Empire', 'Mortar','Special' , 100, 1, 1),
    ('The Empire', 'Flagellants','Special' , 12, 10, 100),
    ('The Empire', 'Helblaster Volley Gun','Special' , 120, 1, 1),
    ('The Empire', 'Helstorm Rocket Battery','Special' , 120, 1, 1),
    ('The Empire', 'Steam Tank','Special' , 250, 1, 1),
    ('The Empire', 'Celestial Hurricanum','Special' , 130, 1, 1),
    ('The Empire', 'Luminark of Hysh','Special' , 120, 1, 1);

INSERT INTO profiles (unit_id, profile_name, movement_allowance, weapon_skill, ballistic_skill, strength, toughness, wounds, initiative, attacks, leadership, troop_type, max_per_unit) VALUES (
    (SELECT unit_id from units WHERE unit_name = 'Karl Franz, The Emperor'), 'Karl Franz', '4', 6, 5, 4, 4, 3, 6, '4', 10, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Karl Franz, The Emperor'), 'Deathclaw', '6', 6, 0, 6, 5, 5, 4, '5', 8, 'Monster', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kurt Helborg, Reiksmarshal of the Empire'), 'Kurt Helborg', '4', 7, 6, 4, 4, 3, 6, '4', 9, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Kurt Helborg, Reiksmarshal of the Empire'), 'Krieglust(Warhorse)', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Balthasar Gelt, The Supreme Patriarch'), 'Balthasar Gelt', '4', 3, 3, 3, 4, 3, 3, '1', 8, 'Monstrous Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Balthasar Gelt, The Supreme Patriarch'), 'Imperial Pegasus', '8', 3, 0, 4, 4, 3, 4, '2', 6, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Volkmar the Grim, The Grand Theogonist'), 'Volkmar the Grim', '4', 5, 4, 4, 4, 3, 4, '2', 9, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Marius Leitdorf'), 'Marius Leitdorf', '4', 6, 5, 4, 4, 3, 5, '3', 9, 'Cavalry(Special Character; General of the Empire)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Marius Leitdorf'), 'Daisy(Warhorse)', '8', 3, 0, 3, 3, 1, 3, '1', '5', null, 1),
    ((SELECT unit_id from units WHERE unit_name ='General of the Empire'), 'General of the Empire', '4', 5, 5, 4, 4, 3, 5, '3', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Battle Wizard Lord'), 'Battle Wizard Lord', '4', 3, 3, 3, 4, 3, 3, '1', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Arch Lector'), 'Arch Lector', '4', 4, 4, 4, 4, 3, 4, '2', 9, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grand Master'), 'Grand Master', '4', 6, 6, 4, 4, 3, 6, '4', 9, 'Cavalry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Grand Master'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Ludwig Schwarzhelm, The Emperor`s Champion'), 'Ludwig Schwarzhelm', '4', 6, 5, 4, 4, 2, 5, '3', 8, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Ludwig Schwarzhelm, The Emperor`s Champion'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Luthor Huss, Prophet of Sigmar'), 'Luthor Huss', '4', 5, 4, 4, 4, 2, 4, '2', 8, 'Cavalry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Luthor Huss, Prophet of Sigmar'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Markus Wulfhart, Huntsmarshal of the Empire'), 'Markus Wulfhart', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Special Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Captain of the Empire'), 'Captain of the Empire', '4', 5, 5, 4, 4, 2, 5, '3', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Battle Wizard'), 'Battle Wizard', '4', 3, 3, 3, 3, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Warrior Priest'), 'Warrior Priest', '4', 4, 4, 4, 4, 2, 4, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Master Engineer' AND faction = 'The Empire'), 'Master Engineer', '4', 3, 4, 3, 3, 2, 3, '1', 7, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Witch Hunter'), 'Witch Hunter', '4', 4, 4, 4, 4, 2, 4, '2', 8, 'Infantry(Character)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Halberdiers'), 'Empire Soldier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Halberdiers'), 'Sergeant', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Spearmen' AND faction = 'The Empire'), 'Empire Soldier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Spearmen' AND faction = 'The Empire'), 'Sergeant', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Swordsmen'), 'Empire Swordsman', '4', 4, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Swordsmen'), 'Duellist', '4', 4, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Crossbowmen' AND faction = 'The Empire'), 'Empire Soldier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Crossbowmen' AND faction = 'The Empire'), 'Marksman', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Handgunners'), 'Empire Soldier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Handgunners'), 'Marksman', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Archers' AND faction = 'The Empire'), 'Empire Soldier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Archers' AND faction = 'The Empire'), 'Marksman', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Free Company Militia'), 'Militia Fighter', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 100),
    ((SELECT unit_id from units WHERE unit_name ='Free Company Militia'), 'Militia Leader', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knightly Orders'), 'Empire Knight', '4', 4, 3, 3, 3, 1, 3, '1', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Knightly Orders'), 'Preceptor', '4', 4, 3, 3, 3, 1, 3, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knightly Orders'), 'Inner Circle Knight', '4', 4, 3, 4, 3, 1, 3, '1', 8, 'Cavalry', 50),
    ((SELECT unit_id from units WHERE unit_name ='Knightly Orders'), 'Inner Circle Preceptor', '4', 4, 3, 4, 3, 1, 3, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Knightly Orders'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 50),
    ((SELECT unit_id from units WHERE unit_name ='Greatswords'), 'Greatsword','4', 4, 3, 3, 3, 1, 3, '1', 8, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Greatswords'), 'Count´s Champion', '4', 4, 3, 3, 3, 1, 3, '2', 8, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Demigryph Knights'), 'Inner Circle Knight', '4', 4, 3, 4, 3, 1, 3, '1', 8, 'Monstrous Cavalry', 3),
    ((SELECT unit_id from units WHERE unit_name ='Demigryph Knights'), 'Inner Circle Preceptor', '4', 4, 3, 4, 3, 1, 3, '2', 8, 'Monstrous Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Demigryph Knights'), 'Demigryph','8', 4, 0, 5, 4, 3, 4, '3', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Reiksguard Knights'), 'Reiksguard Knight', '4', 4, 3, 4, 3, 1, 3, '1', 8, 'Cavalry', 5),
    ((SELECT unit_id from units WHERE unit_name ='Reiksguard Knights'), 'Reikscaptain', '4', 4, 3, 4, 3, 1, 3, '2', 8, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Reiksguard Knights'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 5),
    ((SELECT unit_id from units WHERE unit_name ='Huntsmen'), 'Huntsman', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Huntsmen'), 'Tracker', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Pistoliers'), 'Pistolier', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Cavalry', 5),
    ((SELECT unit_id from units WHERE unit_name ='Pistoliers'), 'Outrider', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Pistoliers'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 5),
    ((SELECT unit_id from units WHERE unit_name ='Outriders'), 'Outrider', '4', 3, 4, 3, 3, 1, 3, '1', 7, 'Cavalry', 5),
    ((SELECT unit_id from units WHERE unit_name ='Outriders'), 'Sharpshooter', '4', 3, 5, 3, 3, 1, 3, '1', 7, 'Cavalry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Outriders'), 'Warhorse', '8', 3, 0, 3, 3, 1, 3, '1', 5, null, 5),
    ((SELECT unit_id from units WHERE unit_name ='Great Cannon'), 'Great Cannon', null, null, null, null, 7, 3, null, null, null, 'War Machine (Great Cannon)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Great Cannon'), 'Crewman', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortar'), 'Mortar', null, null, null, null, 7, 3, null, null, null, 'War Machine (Stone Thrower)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Mortar'), 'Crewman', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Flagellants'), 'Flagellant', '4', 3, 3, 3, 3, 1, 3, '1', 7, 'Infantry', 10),
    ((SELECT unit_id from units WHERE unit_name ='Flagellants'), 'Prophet of Doom', '4', 3, 3, 3, 3, 1, 3, '2', 7, 'Infantry', 1),
    ((SELECT unit_id from units WHERE unit_name ='Helblaster Volley Gun'), 'Helblaster Volley Gun', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Helblaster Volley Gun'), 'Crewman', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Helstorm Rocket Battery'), 'Helstorm Rocket Battery', null, null, null, null, 7, 3, null, null, null, 'War Machine', 1),
    ((SELECT unit_id from units WHERE unit_name ='Helstorm Rocket Battery'), 'Crewman', '4', 3, 3, 3, 3, 1, 3, '1', 7, null, 3),
    ((SELECT unit_id from units WHERE unit_name ='Steam Tank'), 'Steam Tank', '0/Var', null, null, 6, 6, 10, null, null, null, 'Chariot (Armour Save 1+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Steam Tank'), 'Spear Chukka', null, 3, 4, 3, null, null, 3, '1', 7, null, 1),
    ((SELECT unit_id from units WHERE unit_name ='Celestial Hurricanum'), 'Celestial Hurricanum', null, null, null, 5, 5, 5, null, null, null, 'Chariot (Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Celestial Hurricanum'), 'Acolyte', null, 3, 3, 3, null, null, 3, '1', 7, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Celestial Hurricanum'), 'Warhorse', '8', 3, null, 3, null, null, 3, '1', 5, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Luminark of Hysh'), 'Luminark of Hysh', null, null, null, 5, 5, 5, null, null, null, 'Chariot (Armour Save 5+)', 1),
    ((SELECT unit_id from units WHERE unit_name ='Luminark of Hysh'), 'Acolyte', null, 3, 3, 3, null, null, 3, '1', 7, null, 2),
    ((SELECT unit_id from units WHERE unit_name ='Luminark of Hysh'), 'Warhorse', '8', 3, null, 3, null, null, 3, '1', 5, null, 2);
